languageDictionary = {
    "ar_SA": {
        "Weather:": "الطقس:",
        "Your community": "مجتمعك",
        "Find": "ابحث",
        "Add": "أضف",
        "Currency:": "العملة:",
        "Your money": "أموالك",
        "Result: ": "النتيجة:",
        "Translate": "ترجم",
        "About": "حول",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "الأخبار\nالإصدار: 1.0.0\nشركة: OrgInfoTech",
        "Weather today: ": "الطقس اليوم:",
        "Weather tomorrow: ": "طقس الغد:",
        "Go to news": "انتقل إلى الأخبار",
        "No news articles available": "لا يوجد مقالات أخبار متاحة",
        "Failed to fetch news. Please try again later": "فشل في جلب الأخبار. يرجى المحاولة لاحقًا",
        "Converted amount:": "المبلغ المحول:",
        "In community": "في المجتمع",
        "Today": "اليوم",
        "Tomorrow": "غدًا",
        "Clouds": "غيوم",
        "Pressure": "ضغط",
        "Visibility": "رؤية",
        "Temperature (Minimum)": "درجة الحرارة (الأدنى)",
        "Temperature (Maximum)": "درجة الحرارة (الأعلى)"
    },
    "hy_AM": {
        "Weather:": "Եղանակը:",
        "Your community": "Ձեր համայնքը",
        "Find": "Գտնել",
        "Add": "Ավելացնել",
        "Currency:": "Արժույթը:",
        "Your money": "Ձեր փողերը",
        "Result: ": "Արդյունքը:",
        "Translate": "Թարգմանել",
        "About": "Մասին",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Նորություններ\nՏարեթիվ: 1.0.0\nԿազմակերպություն: OrgInfoTech",
        "Weather today: ": "Եղանակը այսօր:",
        "Weather tomorrow: ": "Եղանակը վաղը:",
        "Go to news": "Գնալ նորություններին",
        "No news articles available": "Արձանագրություններ չկան",
        "Failed to fetch news. Please try again later": "Չհաջողվեց բեռնել նորություններ։ Խնդրում ենք փորձել ավելի ուշ",
        "Converted amount:": "Փոխարկված գումար:",
        "In community": "Համայնքում",
        "Today": "Այսօր",
        "Tomorrow": "Վաղը",
        "Clouds": "Ամպեր",
        "Pressure": "Ճնշում",
        "Visibility": "Տեսանելիություն",
        "Temperature (Minimum)": "Ջերմաստիճան (մինիմում)",
        "Temperature (Maximum)": "Ջերմաստիճան (մաքսիմում)"
    },
    "az_AZ": {
        "Weather:": "Hava:",
        "Your community": "İcma",
        "Find": "Tap",
        "Add": "Əlavə et",
        "Currency:": "Valyuta:",
        "Your money": "Pulun",
        "Result: ": "Nəticə:",
        "Translate": "Tərcümə et",
        "About": "Haqqında",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Xəbərlər\nVersiya: 1.0.0\nŞirkət: OrgInfoTech",
        "Weather today: ": "Bugünkü hava:",
        "Weather tomorrow: ": "Sabahkı hava:",
        "Go to news": "Xəbərlərə get",
        "No news articles available": "Xəbər məqalələri yoxdur",
        "Failed to fetch news. Please try again later": "Xəbərləri əldə edə bilmədim. Zəhmət olmasa, bir az sonra cəhd edin",
        "Converted amount:": "Dəyişdirilmiş məbləğ:",
        "In community": "İcmada",
        "Today": "Bu gün",
        "Tomorrow": "Sabah",
        "Clouds": "Bulud",
        "Pressure": "Təzyiq",
        "Visibility": "Görünmə",
        "Temperature (Minimum)": "Temperatur (minimum)",
        "Temperature (Maximum)": "Temperatur (maksimum)"
    },
    "bg_BG": {
        "Weather:": "Времето:",
        "Your community": "Вашата общност",
        "Find": "Намери",
        "Add": "Добави",
        "Currency:": "Валута:",
        "Your money": "Вашите пари",
        "Result: ": "Резултат:",
        "Translate": "Преведи",
        "About": "Относно",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Новини\nВерсия: 1.0.0\nКомпания: OrgInfoTech",
        "Weather today: ": "Времето днес:",
        "Weather tomorrow: ": "Времето утре:",
        "Go to news": "Отиди на новините",
        "No news articles available": "Няма налични новини",
        "Failed to fetch news. Please try again later": "Не успя да зареди новините. Моля, опитайте по-късно",
        "Converted amount:": "Конвертирана сума:",
        "In community": "В общността",
        "Today": "Днес",
        "Tomorrow": "Утре",
        "Clouds": "Облаци",
        "Pressure": "Налягане",
        "Visibility": "Видимост",
        "Temperature (Minimum)": "Температура (минимум)",
        "Temperature (Maximum)": "Температура (максимум)"
    },
    "zh_CN": {
        "Weather:": "天气:",
        "Your community": "您的社区",
        "Find": "查找",
        "Add": "添加",
        "Currency:": "货币:",
        "Your money": "你的钱",
        "Result: ": "结果:",
        "Translate": "翻译",
        "About": "关于",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "新闻\n版本: 1.0.0\n公司: OrgInfoTech",
        "Weather today: ": "今天的天气: ",
        "Weather tomorrow: ": "明天的天气: ",
        "Go to news": "转到新闻",
        "No news articles available": "没有新闻文章可用",
        "Failed to fetch news. Please try again later": "获取新闻失败。请稍后再试",
        "Converted amount:": "转换后的金额:",
        "In community": "在社区",
        "Today": "今天",
        "Tomorrow": "明天",
        "Clouds": "云",
        "Pressure": "压力",
        "Visibility": "能见度",
        "Temperature (Minimum)": "最低温度",
        "Temperature (Maximum)": "最高温度"
    },
    "zh_TW": {
        "Weather:": "天氣:",
        "Your community": "您的社區",
        "Find": "查找",
        "Add": "添加",
        "Currency:": "貨幣:",
        "Your money": "您的金錢",
        "Result: ": "結果:",
        "Translate": "翻譯",
        "About": "關於",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "新聞\n版本: 1.0.0\n公司: OrgInfoTech",
        "Weather today: ": "今天的天氣:",
        "Weather tomorrow: ": "明天的天氣:",
        "Go to news": "前往新聞",
        "No news articles available": "沒有可用的新聞",
        "Failed to fetch news. Please try again later": "未能獲取新聞。請稍後再試",
        "Converted amount:": "兌換後金額:",
        "In community": "在社區內",
        "Today": "今天",
        "Tomorrow": "明天",
        "Clouds": "雲",
        "Pressure": "氣壓",
        "Visibility": "能見度",
        "Temperature (Minimum)": "溫度（最低）",
        "Temperature (Maximum)": "溫度（最高）"
    },
    "hr_HR": {
        "Weather:": "Vrijeme:",
        "Your community": "Vaša zajednica",
        "Find": "Pronađi",
        "Add": "Dodaj",
        "Currency:": "Valuta:",
        "Your money": "Vaš novac",
        "Result: ": "Rezultat:",
        "Translate": "Prevedi",
        "About": "O",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Vijesti\nVerzija: 1.0.0\nTvrtka: OrgInfoTech",
        "Weather today: ": "Vrijeme danas:",
        "Weather tomorrow: ": "Vrijeme sutra:",
        "Go to news": "Idi na vijesti",
        "No news articles available": "Nema dostupnih vijesti",
        "Failed to fetch news. Please try again later": "Neuspjelo dohvaćanje vijesti. Pokušajte kasnije",
        "Converted amount:": "Konvertirani iznos:",
        "In community": "U zajednici",
        "Today": "Danas",
        "Tomorrow": "Sutra",
        "Clouds": "Oblaci",
        "Pressure": "Tlak",
        "Visibility": "Vidljivost",
        "Temperature (Minimum)": "Temperatura (minimum)",
        "Temperature (Maximum)": "Temperatura (maksimum)"
    },
    "cs_CZ": {
        "Weather:": "Počasí:",
        "Your community": "Vaše komunita",
        "Find": "Najít",
        "Add": "Přidat",
        "Currency:": "Měna:",
        "Your money": "Vaše peníze",
        "Result: ": "Výsledek: ",
        "Translate": "Přeložit",
        "About": "O nás",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Zprávy\nVerze: 1.0.0\nSpolečnost: OrgInfoTech",
        "Weather today: ": "Počasí dnes:",
        "Weather tomorrow: ": "Počasí zítra:",
        "Go to news": "Jít na zprávy",
        "No news articles available": "Žádné dostupné zpravodajské články",
        "Failed to fetch news. Please try again later": "Nepodařilo se získat zprávy. Zkuste to prosím později",
        "Converted amount:": "Převodní částka:",
        "In community": "V komunitě",
        "Today": "Dnes",
        "Tomorrow": "Zítra",
        "Clouds": "Mraky",
        "Pressure": "Tlak",
        "Visibility": "Viditelnost",
        "Temperature (Minimum)": "Teplota (minimum)",
        "Temperature (Maximum)": "Teplota (maximum)"
    },
    "da_DK": {
        "Weather:": "Vejer:",
        "Your community": "Dit samfund",
        "Find": "Find",
        "Add": "Tilføj",
        "Currency:": "Valuta:",
        "Your money": "Dine penge",
        "Result: ": "Resultat: ",
        "Translate": "Oversæt",
        "About": "Om",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Nyheder\nVersion: 1.0.0\nFirma: OrgInfoTech",
        "Weather today: ": "Vejret i dag: ",
        "Weather tomorrow: ": "Vejret i morgen: ",
        "Go to news": "Gå til nyheder",
        "No news articles available": "Ingen nyhedsartikler tilgængelige",
        "Failed to fetch news. Please try again later": "Kunne ikke hente nyheder. Prøv igen senere",
        "Converted amount:": "Konverteret beløb:",
        "In community": "I samfundet",
        "Today": "I dag",
        "Tomorrow": "I morgen",
        "Clouds": "Skyer",
        "Pressure": "Tryk",
        "Visibility": "Sigtbarhed",
        "Temperature (Minimum)": "Temperatur (minimum)",
        "Temperature (Maximum)": "Temperatur (maksimum)"
    },
    "nl_NL": {
        "Weather:": "Weer:",
        "Your community": "Uw gemeenschap",
        "Find": "Zoeken",
        "Add": "Toevoegen",
        "Currency:": "Valuta:",
        "Your money": "Uw geld",
        "Result: ": "Resultaat:",
        "Translate": "Vertalen",
        "About": "Over",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Nieuws\nVersie: 1.0.0\nBedrijf: OrgInfoTech",
        "Weather today: ": "Weer vandaag:",
        "Weather tomorrow: ": "Weer morgen:",
        "Go to news": "Ga naar nieuws",
        "No news articles available": "Geen nieuwsartikelen beschikbaar",
        "Failed to fetch news. Please try again later": "Nieuws ophalen mislukt. Probeer het later opnieuw",
        "Converted amount:": "Omgezet bedrag:",
        "In community": "In gemeenschap",
        "Today": "Vandaag",
        "Tomorrow": "Morgen",
        "Clouds": "Wolken",
        "Pressure": "Druk",
        "Visibility": "Zicht",
        "Temperature (Minimum)": "Temperatuur (minimum)",
        "Temperature (Maximum)": "Temperatuur (maximum)"
    },
    "en_US": {
        "Weather:": "Weather:",
        "Your community": "Your community",
        "Find": "Find",
        "Add": "Add",
        "Currency:": "Currency:",
        "Your money": "Your money",
        "Result: ": "Result:",
        "Translate": "Translate",
        "About": "About",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "News\nVersion: 1.0.0\nCompany: OrgInfoTech",
        "Weather today: ": "Weather today:",
        "Weather tomorrow: ": "Weather tomorrow:",
        "Go to news": "Go to news",
        "No news articles available": "No news articles available",
        "Failed to fetch news. Please try again later": "Failed to fetch news. Please try again later",
        "Converted amount:": "Converted amount:",
        "In community": "In community",
        "Today": "Today",
        "Tomorrow": "Tomorrow",
        "Clouds": "Clouds",
        "Pressure": "Pressure",
        "Visibility": "Visibility",
        "Temperature (Minimum)": "Temperature (Minimum)",
        "Temperature (Maximum)": "Temperature (Maximum)"
    },
    "en_GB": {
        "Weather:": "Weather:",
        "Your community": "Your community",
        "Find": "Find",
        "Add": "Add",
        "Currency:": "Currency:",
        "Your money": "Your money",
        "Result: ": "Result:",
        "Translate": "Translate",
        "About": "About",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "News\nVersion: 1.0.0\nCompany: OrgInfoTech",
        "Weather today: ": "Weather today:",
        "Weather tomorrow: ": "Weather tomorrow:",
        "Go to news": "Go to news",
        "No news articles available": "No news articles available",
        "Failed to fetch news. Please try again later": "Failed to fetch news. Please try again later",
        "Converted amount:": "Converted amount:",
        "In community": "In community",
        "Today": "Today",
        "Tomorrow": "Tomorrow",
        "Clouds": "Clouds",
        "Pressure": "Pressure",
        "Visibility": "Visibility",
        "Temperature (Minimum)": "Temperature (Minimum)",
        "Temperature (Maximum)": "Temperature (Maximum)"
    },
    "en_CA": {
        "Weather:": "Weather:",
        "Your community": "Your community",
        "Find": "Find",
        "Add": "Add",
        "Currency:": "Currency:",
        "Your money": "Your money",
        "Result: ": "Result:",
        "Translate": "Translate",
        "About": "About",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "News\nVersion: 1.0.0\nCompany: OrgInfoTech",
        "Weather today: ": "Weather today:",
        "Weather tomorrow: ": "Weather tomorrow:",
        "Go to news": "Go to news",
        "No news articles available": "No news articles available",
        "Failed to fetch news. Please try again later": "Failed to fetch news. Please try again later",
        "Converted amount:": "Converted amount:",
        "In community": "In community",
        "Today": "Today",
        "Tomorrow": "Tomorrow",
        "Clouds": "Clouds",
        "Pressure": "Pressure",
        "Visibility": "Visibility",
        "Temperature (Minimum)": "Temperature (Minimum)",
        "Temperature (Maximum)": "Temperature (Maximum)"
    },
    "en_AU": {
        "Weather:": "Weather:",
        "Your community": "Your community",
        "Find": "Find",
        "Add": "Add",
        "Currency:": "Currency:",
        "Your money": "Your money",
        "Result: ": "Result:",
        "Translate": "Translate",
        "About": "About",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "News\nVersion: 1.0.0\nCompany: OrgInfoTech",
        "Weather today: ": "Weather today:",
        "Weather tomorrow: ": "Weather tomorrow:",
        "Go to news": "Go to news",
        "No news articles available": "No news articles available",
        "Failed to fetch news. Please try again later": "Failed to fetch news. Please try again later",
        "Converted amount:": "Converted amount:",
        "In community": "In community",
        "Today": "Today",
        "Tomorrow": "Tomorrow",
        "Clouds": "Clouds",
        "Pressure": "Pressure",
        "Visibility": "Visibility",
        "Temperature (Minimum)": "Temperature (Minimum)",
        "Temperature (Maximum)": "Temperature (Maximum)"
    },
    "et_EE": {
        "Weather:": "Ilm:",
        "Your community": "Teie kogukond",
        "Find": "Otsi",
        "Add": "Lisa",
        "Currency:": "Valuuta:",
        "Your money": "Teie raha",
        "Result: ": "Tulemus:",
        "Translate": "Tõlgi",
        "About": "Umbes",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Uudised\nVersioon: 1.0.0\nEttevõte: OrgInfoTech",
        "Weather today: ": "Ilm täna:",
        "Weather tomorrow: ": "Ilm homme:",
        "Go to news": "Minge uudistesse",
        "No news articles available": "Uudiseid pole saadaval",
        "Failed to fetch news. Please try again later": "Uudiste laadimine ebaõnnestus. Proovige hiljem uuesti",
        "Converted amount:": "Muunutatud summa:",
        "In community": "Kogukonnas",
        "Today": "Täna",
        "Tomorrow": "Homme",
        "Clouds": "Pilved",
        "Pressure": "Rõhk",
        "Visibility": "Nägemus",
        "Temperature (Minimum)": "Temperatuur (miinimum)",
        "Temperature (Maximum)": "Temperatuur (maksimum)"
    },
    "fi_FI": {
        "Weather:": "Sää:",
        "Your community": "Yhteisösi",
        "Find": "Etsi",
        "Add": "Lisää",
        "Currency:": "Valuutta:",
        "Your money": "Rahasi",
        "Result: ": "Tulos:",
        "Translate": "Käännä",
        "About": "Tietoja",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Uutiset\nVersio: 1.0.0\nYritys: OrgInfoTech",
        "Weather today: ": "Tämän päivän sää:",
        "Weather tomorrow: ": "Huomisen sää:",
        "Go to news": "Mene uutisiin",
        "No news articles available": "Ei uutisartikkeleita saatavilla",
        "Failed to fetch news. Please try again later": "Uutisten haku epäonnistui. Yritä myöhemmin uudelleen",
        "Converted amount:": "Muunnettu summa:",
        "In community": "Yhteisössä",
        "Today": "Tänään",
        "Tomorrow": "Huomenna",
        "Clouds": "Pilvet",
        "Pressure": "Paine",
        "Visibility": "Näkyvyys",
        "Temperature (Minimum)": "Lämpötila (minimi)",
        "Temperature (Maximum)": "Lämpötila (maksimi)"
    },
    "fr_FR": {
        "Weather:": "Météo:",
        "Your community": "Votre communauté",
        "Find": "Trouver",
        "Add": "Ajouter",
        "Currency:": "Devise:",
        "Your money": "Votre argent",
        "Result: ": "Résultat:",
        "Translate": "Traduire",
        "About": "À propos",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Nouvelles\nVersion: 1.0.0\nCompagnie: OrgInfoTech",
        "Weather today: ": "Météo aujourd'hui:",
        "Weather tomorrow: ": "Météo demain:",
        "Go to news": "Aller aux nouvelles",
        "No news articles available": "Aucun article de presse disponible",
        "Failed to fetch news. Please try again later": "Échec de la récupération des nouvelles. Veuillez réessayer plus tard",
        "Converted amount:": "Montant converti:",
        "In community": "Dans la communauté",
        "Today": "Aujourd'hui",
        "Tomorrow": "Demain",
        "Clouds": "Nuages",
        "Pressure": "Pression",
        "Visibility": "Visibilité",
        "Temperature (Minimum)": "Température (minimum)",
        "Temperature (Maximum)": "Température (maximum)"
    },
    "fr_CA": {
        "Weather:": "Météo:",
        "Your community": "Votre communauté",
        "Find": "Trouver",
        "Add": "Ajouter",
        "Currency:": "Devise:",
        "Your money": "Votre argent",
        "Result: ": "Résultat:",
        "Translate": "Traduire",
        "About": "À propos",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Nouvelles\nVersion: 1.0.0\nCompagnie: OrgInfoTech",
        "Weather today: ": "Météo aujourd'hui:",
        "Weather tomorrow: ": "Météo demain:",
        "Go to news": "Aller aux nouvelles",
        "No news articles available": "Aucun article de presse disponible",
        "Failed to fetch news. Please try again later": "Échec de la récupération des nouvelles. Veuillez réessayer plus tard",
        "Converted amount:": "Montant converti:",
        "In community": "Dans la communauté",
        "Today": "Aujourd'hui",
        "Tomorrow": "Demain",
        "Clouds": "Nuages",
        "Pressure": "Pression",
        "Visibility": "Visibilité",
        "Temperature (Minimum)": "Température (minimum)",
        "Temperature (Maximum)": "Température (maximum)"
    },
    "ka_GE": {
        "Weather:": "ამინდი:",
        "Your community": "თქვენი საზოგადოება",
        "Find": "გადაწი",
        "Add": "დამატება",
        "Currency:": "ვალუტა:",
        "Your money": "თქვენი ფული",
        "Result: ": "შედეგი:",
        "Translate": "თარგმნე",
        "About": "შესახებ",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "სიახლეები\nვერსია: 1.0.0\nკომპანია: OrgInfoTech",
        "Weather today: ": "ამინდები დღეს:",
        "Weather tomorrow: ": "ამინდები ხვალ:",
        "Go to news": "გადადით სიახლეებზე",
        "No news articles available": "სიახლეების არტიკულები არ არის ხელმისაწვდომი",
        "Failed to fetch news. Please try again later": "სიახლეების წამოღება ვერ მოხერხდა. გთხოვთ, სცადოთ მოგვიანებით",
        "Converted amount:": "გადათვლილი რაოდენობა:",
        "In community": "საზოგადოებაში",
        "Today": "დღეს",
        "Tomorrow": "ხვალ",
        "Clouds": "ღრუბლები",
        "Pressure": "წნევა",
        "Visibility": "ხილვადობა",
        "Temperature (Minimum)": "ტემპერატურა (მინიმუმ)",
        "Temperature (Maximum)": "ტემპერატურა (მაქსიმუმ)"
    },
    "de_DE": {
        "Weather:": "Wetter:",
        "Your community": "Ihre Gemeinschaft",
        "Find": "Finden",
        "Add": "Hinzufügen",
        "Currency:": "Währung:",
        "Your money": "Ihr Geld",
        "Result: ": "Ergebnis:",
        "Translate": "Übersetzen",
        "About": "Über",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Nachrichten\nVersion: 1.0.0\nFirma: OrgInfoTech",
        "Weather today: ": "Wetter heute:",
        "Weather tomorrow: ": "Wetter morgen:",
        "Go to news": "Zu den Nachrichten gehen",
        "No news articles available": "Keine Nachrichtenartikel verfügbar",
        "Failed to fetch news. Please try again later": "Nachrichten konnten nicht abgerufen werden. Bitte versuchen Sie es später erneut",
        "Converted amount:": "Konvertierter Betrag:",
        "In community": "In der Gemeinschaft",
        "Today": "Heute",
        "Tomorrow": "Morgen",
        "Clouds": "Wolken",
        "Pressure": "Druck",
        "Visibility": "Sichtweite",
        "Temperature (Minimum)": "Temperatur (Minimum)",
        "Temperature (Maximum)": "Temperatur (Maximum)"
    },
    "el_GR": {
        "Weather:": "Καιρός:",
        "Your community": "Η κοινότητά σας",
        "Find": "Βρείτε",
        "Add": "Προσθέστε",
        "Currency:": "Νόμισμα:",
        "Your money": "Τα χρήματά σας",
        "Result: ": "Αποτέλεσμα:",
        "Translate": "Μετάφραση",
        "About": "Σχετικά",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Ειδήσεις\nΈκδοση: 1.0.0\nΕταιρεία: OrgInfoTech",
        "Weather today: ": "Ο καιρός σήμερα:",
        "Weather tomorrow: ": "Ο καιρός αύριο:",
        "Go to news": "Πηγαίνετε στα νέα",
        "No news articles available": "Δεν υπάρχουν διαθέσιμα άρθρα ειδήσεων",
        "Failed to fetch news. Please try again later": "Αποτυχία φόρτωσης ειδήσεων. Παρακαλώ προσπαθήστε αργότερα",
        "Converted amount:": "Μετατραπέν ποσό:",
        "In community": "Στην κοινότητα",
        "Today": "Σήμερα",
        "Tomorrow": "Αύριο",
        "Clouds": "Σύννεφα",
        "Pressure": "Πίεση",
        "Visibility": "Ορατότητα",
        "Temperature (Minimum)": "Θερμοκρασία (ελάχιστη)",
        "Temperature (Maximum)": "Θερμοκρασία (μέγιστη)"
    },
    "he_IL": {
        "Weather:": "מזג האוויר:",
        "Your community": "הקהילה שלך",
        "Find": "חפש",
        "Add": "הוסף",
        "Currency:": "מטבע:",
        "Your money": "הכסף שלך",
        "Result: ": "תוצאה:",
        "Translate": "תרגם",
        "About": "אודות",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "חדשות\nגרסה: 1.0.0\nחברה: OrgInfoTech",
        "Weather today: ": "מזג האוויר היום:",
        "Weather tomorrow: ": "מזג האוויר מחר:",
        "Go to news": "לך לחדשות",
        "No news articles available": "אין מאמרי חדשות זמינים",
        "Failed to fetch news. Please try again later": "נכשל לקבלת חדשות. אנא נסה שוב מאוחר יותר",
        "Converted amount:": "סכום מומיר:",
        "In community": "בקהילה",
        "Today": "היום",
        "Tomorrow": "מחר",
        "Clouds": "עננים",
        "Pressure": "לחץ",
        "Visibility": "ראות",
        "Temperature (Minimum)": "טמפרטורה (מינימלית)",
        "Temperature (Maximum)": "טמפרטורה (מירבית)"
    },
    "hi_IN": {
        "Weather:": "मौसम:",
        "Your community": "आपका समुदाय",
        "Find": "खोजें",
        "Add": "जोड़ें",
        "Currency:": "मुद्रा:",
        "Your money": "आपके पैसे",
        "Result: ": "परिणाम:",
        "Translate": "अनुवाद करें",
        "About": "के बारे में",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "समाचार\nसंस्करण: 1.0.0\nकंपनी: OrgInfoTech",
        "Weather today: ": "आज का मौसम:",
        "Weather tomorrow: ": "कल का मौसम:",
        "Go to news": "समाचार पर जाएं",
        "No news articles available": "कोई समाचार लेख उपलब्ध नहीं हैं",
        "Failed to fetch news. Please try again later": "समाचार लाने में विफल। कृपया बाद में प्रयास करें",
        "Converted amount:": "परिवर्तित राशि:",
        "In community": "समुदाय में",
        "Today": "आज",
        "Tomorrow": "कल",
        "Clouds": "बादल",
        "Pressure": "दबाव",
        "Visibility": "दृश्यता",
        "Temperature (Minimum)": "तापमान (न्यूनतम)",
        "Temperature (Maximum)": "तापमान (अधिकतम)"
    },
    "hu_HU": {
        "Weather:": "Időjárás:",
        "Your community": "Az Ön közössége",
        "Find": "Keresés",
        "Add": "Hozzáadás",
        "Currency:": "Pénznem:",
        "Your money": "Az Ön pénze",
        "Result: ": "Eredmény:",
        "Translate": "Fordítás",
        "About": "Névjegy",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Hírek\nVerzió: 1.0.0\nCég: OrgInfoTech",
        "Weather today: ": "Mai időjárás:",
        "Weather tomorrow: ": "Holnapi időjárás:",
        "Go to news": "Menj a hírekhez",
        "No news articles available": "Nincsenek elérhető hírcikkek",
        "Failed to fetch news. Please try again later": "Hírek letöltése nem sikerült. Kérjük, próbálja meg később",
        "Converted amount:": "Átváltott összeg:",
        "In community": "Közösségben",
        "Today": "Ma",
        "Tomorrow": "Holnap",
        "Clouds": "Felhők",
        "Pressure": "Nyomás",
        "Visibility": "Láthatóság",
        "Temperature (Minimum)": "Hőmérséklet (minimum)",
        "Temperature (Maximum)": "Hőmérséklet (maximum)"
    },
    "it_IT": {
        "Weather:": "Meteo:",
        "Your community": "La tua comunità",
        "Find": "Cerca",
        "Add": "Aggiungi",
        "Currency:": "Valuta:",
        "Your money": "I tuoi soldi",
        "Result: ": "Risultato:",
        "Translate": "Traduci",
        "About": "Informazioni",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Notizie\nVersione: 1.0.0\nAzienda: OrgInfoTech",
        "Weather today: ": "Meteo oggi:",
        "Weather tomorrow: ": "Meteo domani:",
        "Go to news": "Vai alle notizie",
        "No news articles available": "Nessun articolo di notizie disponibile",
        "Failed to fetch news. Please try again later": "Impossibile recuperare le notizie. Si prega di riprovare più tardi",
        "Converted amount:": "Importo convertito:",
        "In community": "Nella comunità",
        "Today": "Oggi",
        "Tomorrow": "Domani",
        "Clouds": "Nuvole",
        "Pressure": "Pressione",
        "Visibility": "Visibilità",
        "Temperature (Minimum)": "Temperatura (minima)",
        "Temperature (Maximum)": "Temperatura (massima)"
    },
    "ja_JP": {
        "Weather:": "天気:",
        "Your community": "あなたのコミュニティ",
        "Find": "見つける",
        "Add": "追加",
        "Currency:": "通貨:",
        "Your money": "あなたのお金",
        "Result: ": "結果:",
        "Translate": "翻訳",
        "About": "約",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "ニュース\nバージョン: 1.0.0\n会社: OrgInfoTech",
        "Weather today: ": "今日の天気:",
        "Weather tomorrow: ": "明日の天気:",
        "Go to news": "ニュースに移動",
        "No news articles available": "ニュース記事がありません",
        "Failed to fetch news. Please try again later": "ニュースの取得に失敗しました。後でもう一度お試しください",
        "Converted amount:": "換算金額:",
        "In community": "コミュニティで",
        "Today": "今日",
        "Tomorrow": "明日",
        "Clouds": "雲",
        "Pressure": "気圧",
        "Visibility": "視界",
        "Temperature (Minimum)": "最低気温",
        "Temperature (Maximum)": "最高気温"
    },
    "kk_KZ": {
        "Weather:": "Ауа райы:",
        "Your community": "Сіздің қауымдастық",
        "Find": "Іздеу",
        "Add": "Қосу",
        "Currency:": "Валюта:",
        "Your money": "Сіздің ақшаңыз",
        "Result: ": "Нәтиже:",
        "Translate": "Аудару",
        "About": "Туралы",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Жаңалықтар\nНұсқа: 1.0.0\nКомпания: OrgInfoTech",
        "Weather today: ": "Бүгінгі ауа райы:",
        "Weather tomorrow: ": "Ертеңгі ауа райы:",
        "Go to news": "Жаңалықтарға өту",
        "No news articles available": "Жаңалықтар жоқ",
        "Failed to fetch news. Please try again later": "Жаңалықтарды алу мүмкін болмады. Кейінірек қайтадан көріңіз",
        "Converted amount:": "Аударылған сома:",
        "In community": "Қауымдастықта",
        "Today": "Бүгін",
        "Tomorrow": "Ертең",
        "Clouds": "Бұлттар",
        "Pressure": "Қысым",
        "Visibility": "Көріну",
        "Temperature (Minimum)": "Температура (минимум)",
        "Temperature (Maximum)": "Температура (максимум)"
    },
    "ko_KR": {
        "Weather:": "날씨:",
        "Your community": "당신의 지역 사회",
        "Find": "찾다",
        "Add": "추가",
        "Currency:": "통화:",
        "Your money": "당신의 돈",
        "Result: ": "결과: ",
        "Translate": "번역",
        "About": "정보",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "뉴스\n버전: 1.0.0\n회사: OrgInfoTech",
        "Weather today: ": "오늘 날씨: ",
        "Weather tomorrow: ": "내일 날씨: ",
        "Go to news": "뉴스 보러 가기",
        "No news articles available": "뉴스 기사가 없습니다",
        "Failed to fetch news. Please try again later": "뉴스를 가져오는 데 실패했습니다. 나중에 다시 시도하세요",
        "Converted amount:": "전환된 금액:",
        "In community": "커뮤니티에서",
        "Today": "오늘",
        "Tomorrow": "내일",
        "Clouds": "구름",
        "Pressure": "기압",
        "Visibility": "가시거리",
        "Temperature (Minimum)": "최저 온도",
        "Temperature (Maximum)": "최고 온도"
    },
    "ky_KG": {
        "Weather:": "Аба ырайы:",
        "Your community": "Сиздин жамаатыңыз",
        "Find": "Издөө",
        "Add": "Кошуу",
        "Currency:": "Валюта:",
        "Your money": "Сиздин акчаңыз",
        "Result: ": "Натыйжа:",
        "Translate": "Которуу",
        "About": "Жөнүндө",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Жаңылыктар\nНуска: 1.0.0\nКомпания: OrgInfoTech",
        "Weather today: ": "Бүгүнкү аба ырайы:",
        "Weather tomorrow: ": "Эртеңки аба ырайы:",
        "Go to news": "Жаңылыктарга баруу",
        "No news articles available": "Жаңылык макалалары жок",
        "Failed to fetch news. Please try again later": "Жаңылыктарды алуу ишке ашкан жок. Кийинчерээк кайрадан аракет кылыңыз",
        "Converted amount:": "Айландырылган сумма:",
        "In community": "Жамаатта",
        "Today": "Бүгүн",
        "Tomorrow": "Эртең",
        "Clouds": "Булуттар",
        "Pressure": "Басым",
        "Visibility": "Көрүү",
        "Temperature (Minimum)": "Температура (минимум)",
        "Temperature (Maximum)": "Температура (максимум)"
    },
    "lv_LV": {
        "Weather:": "Laiks:",
        "Your community": "Jūsu kopiena",
        "Find": "Meklēt",
        "Add": "Pievienot",
        "Currency:": "Valūta:",
        "Your money": "Jūsu nauda",
        "Result: ": "Rezultāts:",
        "Translate": "Tulkot",
        "About": "Par",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Ziņas\nVersija: 1.0.0\nUzņēmums: OrgInfoTech",
        "Weather today: ": "Šodienas laiks:",
        "Weather tomorrow: ": "Rītdienas laiks:",
        "Go to news": "Dodieties uz ziņām",
        "No news articles available": "Nav pieejamu ziņu rakstu",
        "Failed to fetch news. Please try again later": "Ziņu iegūšana neizdevās. Lūdzu, mēģiniet vēlreiz vēlāk",
        "Converted amount:": "Pārveidotā summa:",
        "In community": "Kopienā",
        "Today": "Šodien",
        "Tomorrow": "Rīt",
        "Clouds": "Mākoņi",
        "Pressure": "Spiediens",
        "Visibility": "Redzamība",
        "Temperature (Minimum)": "Temperatūra (minimālā)",
        "Temperature (Maximum)": "Temperatūra (maksimālā)"
    },
    "lt_LT": {
        "Weather:": "Orai:",
        "Your community": "Jūsų bendruomenė",
        "Find": "Rasti",
        "Add": "Pridėti",
        "Currency:": "Valiuta:",
        "Your money": "Jūsų pinigai",
        "Result: ": "Rezultatas:",
        "Translate": "Versti",
        "About": "Apie",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Naujienos\nVersija: 1.0.0\nĮmonė: OrgInfoTech",
        "Weather today: ": "Orai šiandien:",
        "Weather tomorrow: ": "Orai rytoj:",
        "Go to news": "Eikite į naujienas",
        "No news articles available": "Nėra pasiekiamų naujienų straipsnių",
        "Failed to fetch news. Please try again later": "Naujienų gavimas nepavyko. Bandykite vėliau",
        "Converted amount:": "Pakeista suma:",
        "In community": "Bendruomenėje",
        "Today": "Šiandien",
        "Tomorrow": "Rytoj",
        "Clouds": "Debesys",
        "Pressure": "Slėgis",
        "Visibility": "Matomumas",
        "Temperature (Minimum)": "Temperatūra (minimalus)",
        "Temperature (Maximum)": "Temperatūra (maksimalus)"
    },
    "mn_MN": {
        "Weather:": "Цаг агаар:",
        "Your community": "Таны хамт олон",
        "Find": "Хайх",
        "Add": "Нэмэх",
        "Currency:": "Валют:",
        "Your money": "Таны мөнгө",
        "Result: ": "Үр дүн:",
        "Translate": "Орчуулах",
        "About": "Тухай",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Мэдээ\nХувилбар: 1.0.0\nКомпани: OrgInfoTech",
        "Weather today: ": "Өнөөдрийн цаг агаар:",
        "Weather tomorrow: ": "Маргаашийн цаг агаар:",
        "Go to news": "Мэдээ рүү очих",
        "No news articles available": "Мэдээний нийтлэл байхгүй",
        "Failed to fetch news. Please try again later": "Мэдээг уншихад алдаа гарлаа. Дараа дахин оролдоно уу",
        "Converted amount:": "Хувиргасан хэмжээ:",
        "In community": "Хамт олонд",
        "Today": "Өнөөдөр",
        "Tomorrow": "Маргааш",
        "Clouds": "Үүл",
        "Pressure": "Даралт",
        "Visibility": "Харагдах байдал",
        "Temperature (Minimum)": "Температур (хамгийн бага)",
        "Temperature (Maximum)": "Температур (хамгийн их)"
    },
    "fa_IR": {
        "Weather:": "هوا:",
        "Your community": "جامعه شما",
        "Find": "پیدا کنید",
        "Add": "اضافه کردن",
        "Currency:": "واحد پول:",
        "Your money": "پول شما",
        "Result: ": "نتیجه:",
        "Translate": "ترجمه کنید",
        "About": "درباره",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "اخبار\nنسخه: 1.0.0\nشرکت: OrgInfoTech",
        "Weather today: ": "هوا امروز:",
        "Weather tomorrow: ": "هوا فردا:",
        "Go to news": "به اخبار بروید",
        "No news articles available": "هیچ مقاله خبری در دسترس نیست",
        "Failed to fetch news. Please try again later": "مشکلی در دریافت اخبار به وجود آمده است. لطفاً بعداً امتحان کنید",
        "Converted amount:": "مبلغ تبدیل شده:",
        "In community": "در جامعه",
        "Today": "امروز",
        "Tomorrow": "فردا",
        "Clouds": "ابرها",
        "Pressure": "فشار",
        "Visibility": "دید",
        "Temperature (Minimum)": "دما (حداقل)",
        "Temperature (Maximum)": "دما (حداکثر)"
    },
    "pl_PL": {
        "Weather:": "Pogoda:",
        "Your community": "Twoja społeczność",
        "Find": "Szukaj",
        "Add": "Dodaj",
        "Currency:": "Waluta:",
        "Your money": "Twoje pieniądze",
        "Result: ": "Wynik:",
        "Translate": "Przetłumacz",
        "About": "O aplikacji",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Wiadomości\nWersja: 1.0.0\nFirma: OrgInfoTech",
        "Weather today: ": "Pogoda dziś:",
        "Weather tomorrow: ": "Pogoda jutro:",
        "Go to news": "Przejdź do wiadomości",
        "No news articles available": "Brak dostępnych artykułów informacyjnych",
        "Failed to fetch news. Please try again later": "Nie udało się pobrać wiadomości. Spróbuj ponownie później",
        "Converted amount:": "Przeliczona kwota:",
        "In community": "W społeczności",
        "Today": "Dziś",
        "Tomorrow": "Jutro",
        "Clouds": "Chmury",
        "Pressure": "Ciśnienie",
        "Visibility": "Widoczność",
        "Temperature (Minimum)": "Temperatura (minimalna)",
        "Temperature (Maximum)": "Temperatura (maksymalna)"
    },
    "pt_PT": {
        "Weather:": "Tempo:",
        "Your community": "A sua comunidade",
        "Find": "Encontrar",
        "Add": "Adicionar",
        "Currency:": "Moeda:",
        "Your money": "O seu dinheiro",
        "Result: ": "Resultado:",
        "Translate": "Traduzir",
        "About": "Sobre",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Notícias\nVersão: 1.0.0\nEmpresa: OrgInfoTech",
        "Weather today: ": "Tempo hoje:",
        "Weather tomorrow: ": "Tempo amanhã:",
        "Go to news": "Ir para notícias",
        "No news articles available": "Nenhum artigo noticioso disponível",
        "Failed to fetch news. Please try again later": "Falha ao buscar notícias. Tente novamente mais tarde",
        "Converted amount:": "Montante convertido:",
        "In community": "Na comunidade",
        "Today": "Hoje",
        "Tomorrow": "Amanhã",
        "Clouds": "Nuvens",
        "Pressure": "Pressão",
        "Visibility": "Visibilidade",
        "Temperature (Minimum)": "Temperatura (mínima)",
        "Temperature (Maximum)": "Temperatura (máxima)"
    },
    "pt_BR": {
        "Weather:": "Tempo:",
        "Your community": "Sua comunidade",
        "Find": "Encontrar",
        "Add": "Adicionar",
        "Currency:": "Moeda:",
        "Your money": "Seu dinheiro",
        "Result: ": "Resultado:",
        "Translate": "Traduzir",
        "About": "Sobre",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Notícias\nVersão: 1.0.0\nEmpresa: OrgInfoTech",
        "Weather today: ": "Tempo hoje:",
        "Weather tomorrow: ": "Tempo amanhã:",
        "Go to news": "Ir para as notícias",
        "No news articles available": "Nenhum artigo de notícias disponível",
        "Failed to fetch news. Please try again later": "Falha ao buscar notícias. Tente novamente mais tarde",
        "Converted amount:": "Quantia convertida:",
        "In community": "Na comunidade",
        "Today": "Hoje",
        "Tomorrow": "Amanhã",
        "Clouds": "Nuvens",
        "Pressure": "Pressão",
        "Visibility": "Visibilidade",
        "Temperature (Minimum)": "Temperatura (mínima)",
        "Temperature (Maximum)": "Temperatura (máxima)"
    },
    "ro_RO": {
        "Weather:": "Vremea:",
        "Your community": "Comunitatea ta",
        "Find": "Găsiți",
        "Add": "Adaugă",
        "Currency:": "Valută:",
        "Your money": "Banii tăi",
        "Result: ": "Rezultat:",
        "Translate": "Traduceți",
        "About": "Despre",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Știri\nVersiune: 1.0.0\nCompanie: OrgInfoTech",
        "Weather today: ": "Vremea astăzi:",
        "Weather tomorrow: ": "Vremea mâine:",
        "Go to news": "Mergi la știri",
        "No news articles available": "Nu există articole de știri disponibile",
        "Failed to fetch news. Please try again later": "Nu s-a putut prelua știri. Încercați din nou mai târziu",
        "Converted amount:": "Suma convertită:",
        "In community": "În comunitate",
        "Today": "Astăzi",
        "Tomorrow": "Mâine",
        "Clouds": "Nori",
        "Pressure": "Presiune",
        "Visibility": "Vizibilitate",
        "Temperature (Minimum)": "Temperatura (minim)",
        "Temperature (Maximum)": "Temperatura (maxim)"
    },
    "ru_RU": {
        "Weather:": "Погода:",
        "Your community": "Ваше сообщество",
        "Find": "Найти",
        "Add": "Добавить",
        "Currency:": "Валюта:",
        "Your money": "Ваши деньги",
        "Result: ": "Результат: ",
        "Translate": "Перевести",
        "About": "О",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Новости\nВерсия: 1.0.0\nКомпания: OrgInfoTech",
        "Weather today: ": "Погода сегодня: ",
        "Weather tomorrow: ": "Погода завтра: ",
        "Go to news": "Перейти к новостям",
        "No news articles available": "Нет доступных новостных статей",
        "Failed to fetch news. Please try again later": "Не удалось получить новости. Пожалуйста, попробуйте позже",
        "Converted amount:": "Конвертированная сумма:",
        "In community": "В сообществе",
        "Today": "Сегодня",
        "Tomorrow": "Завтра",
        "Clouds": "Облака",
        "Pressure": "Давление",
        "Visibility": "Видимость",
        "Temperature (Minimum)": "Температура (минимум)",
        "Temperature (Maximum)": "Температура (максимум)"
    },
    "sr_RS": {
        "Weather:": "Време:",
        "Your community": "Ваша заједница",
        "Find": "Пронађи",
        "Add": "Додај",
        "Currency:": "Валута:",
        "Your money": "Ваш новац",
        "Result: ": "Резултат:",
        "Translate": "Превести",
        "About": "О нама",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Вести\nВерзија: 1.0.0\nКомпанија: OrgInfoTech",
        "Weather today: ": "Време данас:",
        "Weather tomorrow: ": "Време сутра:",
        "Go to news": "Иди на вести",
        "No news articles available": "Нема доступних новинских чланака",
        "Failed to fetch news. Please try again later": "Не могу да преузмем вести. Молимо покушајте касније",
        "Converted amount:": "Конвертована количина:",
        "In community": "У заједници",
        "Today": "Данас",
        "Tomorrow": "Сутра",
        "Clouds": "Облаци",
        "Pressure": "Притисак",
        "Visibility": "Видљивост",
        "Temperature (Minimum)": "Температура (минимум)",
        "Temperature (Maximum)": "Температура (максимум)"
    },
    "sr_RS_latin": {
        "Weather:": "Vreme:",
        "Your community": "Vaša zajednica",
        "Find": "Pronađi",
        "Add": "Dodaj",
        "Currency:": "Valuta:",
        "Your money": "Vaš novac",
        "Result: ": "Rezultat:",
        "Translate": "Prevedi",
        "About": "O nama",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Vesti\nVerzija: 1.0.0\nKompanija: OrgInfoTech",
        "Weather today: ": "Vreme danas:",
        "Weather tomorrow: ": "Vreme sutra:",
        "Go to news": "Idi na vesti",
        "No news articles available": "Nema dostupnih vesti",
        "Failed to fetch news. Please try again later": "Neuspeh u preuzimanju vesti. Pokušajte kasnije",
        "Converted amount:": "Konvertovana suma:",
        "In community": "U zajednici",
        "Today": "Danas",
        "Tomorrow": "Sutra",
        "Clouds": "Oblaci",
        "Pressure": "Pritisak",
        "Visibility": "Vidljivost",
        "Temperature (Minimum)": "Temperatura (minimalna)",
        "Temperature (Maximum)": "Temperatura (maksimalna)"
    },
    "sk_SK": {
        "Weather:": "Počasie:",
        "Your community": "Vaša komunita",
        "Find": "Nájsť",
        "Add": "Pridať",
        "Currency:": "Mena:",
        "Your money": "Vaše peniaze",
        "Result: ": "Výsledok:",
        "Translate": "Preložiť",
        "About": "O",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Správy\nVerzia: 1.0.0\nSpoločnosť: OrgInfoTech",
        "Weather today: ": "Počasie dnes:",
        "Weather tomorrow: ": "Počasie zajtra:",
        "Go to news": "Prejsť na správy",
        "No news articles available": "Nie sú k dispozícii žiadne novinové články",
        "Failed to fetch news. Please try again later": "Nepodarilo sa načítať správy. Skúste to prosím neskôr",
        "Converted amount:": "Konvertovaná suma:",
        "In community": "V komunite",
        "Today": "Dnes",
        "Tomorrow": "Zajtra",
        "Clouds": "Mraky",
        "Pressure": "Tlak",
        "Visibility": "Viditeľnosť",
        "Temperature (Minimum)": "Teplota (minimum)",
        "Temperature (Maximum)": "Teplota (maximum)"
    },
    "sl_SI": {
        "Weather:": "Vreme:",
        "Your community": "Vaša skupnost",
        "Find": "Najdi",
        "Add": "Dodaj",
        "Currency:": "Valuta:",
        "Your money": "Vaš denar",
        "Result: ": "Rezultat:",
        "Translate": "Prevedi",
        "About": "O",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Novice\nRazličica: 1.0.0\nPodjetje: OrgInfoTech",
        "Weather today: ": "Vreme danes:",
        "Weather tomorrow: ": "Vreme jutri:",
        "Go to news": "Pojdi na novice",
        "No news articles available": "Ni na voljo nobenih novic",
        "Failed to fetch news. Please try again later": "Ni uspelo pridobiti novic. Prosimo, poskusite kasneje",
        "Converted amount:": "Pretvorjen znesek:",
        "In community": "V skupnosti",
        "Today": "Danes",
        "Tomorrow": "Jutri",
        "Clouds": "Oblaki",
        "Pressure": "Tlak",
        "Visibility": "Vidljivost",
        "Temperature (Minimum)": "Temperatura (minimalna)",
        "Temperature (Maximum)": "Temperatura (maksimalna)"
    },
    "es_ES": {
        "Weather:": "Tiempo:",
        "Your community": "Tu comunidad",
        "Find": "Buscar",
        "Add": "Añadir",
        "Currency:": "Moneda:",
        "Your money": "Tu dinero",
        "Result: ": "Resultado:",
        "Translate": "Traducir",
        "About": "Acerca de",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Noticias\nVersión: 1.0.0\nCompañía: OrgInfoTech",
        "Weather today: ": "El tiempo hoy:",
        "Weather tomorrow: ": "El tiempo mañana:",
        "Go to news": "Ir a las noticias",
        "No news articles available": "No hay artículos de noticias disponibles",
        "Failed to fetch news. Please try again later": "Falló al obtener noticias. Intente de nuevo más tarde",
        "Converted amount:": "Cantidad convertida:",
        "In community": "En comunidad",
        "Today": "Hoy",
        "Tomorrow": "Mañana",
        "Clouds": "Nubes",
        "Pressure": "Presión",
        "Visibility": "Visibilidad",
        "Temperature (Minimum)": "Temperatura (Mínima)",
        "Temperature (Maximum)": "Temperatura (Máxima)"
    },
    "sv_SE": {
        "Weather:": "Väder:",
        "Your community": "Din gemenskap",
        "Find": "Hitta",
        "Add": "Lägg till",
        "Currency:": "Valuta:",
        "Your money": "Dina pengar",
        "Result: ": "Resultat:",
        "Translate": "Översätt",
        "About": "Om",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Nyheter\nVersion: 1.0.0\nFöretag: OrgInfoTech",
        "Weather today: ": "Vädret idag:",
        "Weather tomorrow: ": "Vädret imorgon:",
        "Go to news": "Gå till nyheter",
        "No news articles available": "Inga nyhetsartiklar tillgängliga",
        "Failed to fetch news. Please try again later": "Misslyckades med att hämta nyheter. Försök igen senare",
        "Converted amount:": "Omräknat belopp:",
        "In community": "I gemenskapen",
        "Today": "Idag",
        "Tomorrow": "Imorgon",
        "Clouds": "Moln",
        "Pressure": "Tryck",
        "Visibility": "Sikt",
        "Temperature (Minimum)": "Temperatur (minimum)",
        "Temperature (Maximum)": "Temperatur (maximum)"
    },
    "tt_RU": {
        "Weather:": "Һава торышы:",
        "Your community": "Сезнең җәмгыять",
        "Find": "Табу",
        "Add": "Өстәү",
        "Currency:": "Валюта:",
        "Your money": "Сезнең акча",
        "Result: ": "Нәтиҗә:",
        "Translate": "Тәрҗемә итү",
        "About": "Турында",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Яңалыклар\nВерсия: 1.0.0\nКомпания: OrgInfoTech",
        "Weather today: ": "Бүген һава торышы:",
        "Weather tomorrow: ": "Иртәгә һава торышы:",
        "Go to news": "Яңалыкларга күчү",
        "No news articles available": "Яңалык мәкаләләре юк",
        "Failed to fetch news. Please try again later": "Яңалыкларны алу мөмкин булмады. Соңрак тагын бер мәртәбә карагыз",
        "Converted amount:": "Әйләндерелгән сумма:",
        "In community": "Җәмгыятьтә",
        "Today": "Бүген",
        "Tomorrow": "Иртәгә",
        "Clouds": "Болытлар",
        "Pressure": "Басым",
        "Visibility": "Күрү",
        "Temperature (Minimum)": "Температура (минималь)",
        "Temperature (Maximum)": "Температура (максималь)"
    },
    "th_TH": {
        "Weather:": "สภาพอากาศ:",
        "Your community": "ชุมชนของคุณ",
        "Find": "ค้นหา",
        "Add": "เพิ่ม",
        "Currency:": "สกุลเงิน:",
        "Your money": "เงินของคุณ",
        "Result: ": "ผลลัพธ์:",
        "Translate": "แปล",
        "About": "เกี่ยวกับ",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "ข่าว\nเวอร์ชัน: 1.0.0\nบริษัท: OrgInfoTech",
        "Weather today: ": "สภาพอากาศวันนี้:",
        "Weather tomorrow: ": "สภาพอากาศพรุ่งนี้:",
        "Go to news": "ไปที่ข่าว",
        "No news articles available": "ไม่มีบทความข่าว",
        "Failed to fetch news. Please try again later": "ไม่สามารถรับข่าวได้ กรุณาลองใหม่ในภายหลัง",
        "Converted amount:": "จำนวนเงินแปลง:",
        "In community": "ในชุมชน",
        "Today": "วันนี้",
        "Tomorrow": "พรุ่งนี้",
        "Clouds": "เมฆ",
        "Pressure": "ความดัน",
        "Visibility": "ทัศนวิสัย",
        "Temperature (Minimum)": "อุณหภูมิ (ต่ำสุด)",
        "Temperature (Maximum)": "อุณหภูมิ (สูงสุด)"
    },
    "bo_CN": {
        "Weather:": "དུས་ཀུལ།:",
        "Your community": "ཁོང་ཚོགས།",
        "Find": "ཞིབ་འཚོལ།",
        "Add": "ཁ་སྦྲད།",
        "Currency:": "སྒོར་མོང་།:",
        "Your money": "ཁོང་དང་། རྒོལ་པོར།",
        "Result: ": "འབྲས་འབྲིང་།:",
        "Translate": "ཨནམག་བཟང་།",
        "About": "ཞིང་གོག་",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "གྱིས་མཐོན་པ། དང་པོ་: 1.0.0\nལས་ཚན: OrgInfoTech",
        "Weather today: ": "དིང་སྟོད་ཀུལ།:",
        "Weather tomorrow: ": "ཉིན་ཚོར་ཀུལ།:",
        "Go to news": "གི་གནས་",
        "No news articles available": "གི་ནང་གིས་གོགས་གནས་བོད།",
        "Failed to fetch news. Please try again later": "གོགས་གནས་སྤུལ་གྱིར་བོད་བོད། དགོས་དེ་ན་ནང་དོན་",
        "Converted amount:": "གནད་སྟོན་པར།:",
        "In community": "ཁོང་ཚོགས།",
        "Today": "དིང་སྟོད",
        "Tomorrow": "ཉིན་ཚོར",
        "Clouds": "བྱེད་ཁྲག",
        "Pressure": "གདོད་འགྱུར",
        "Visibility": "གྱངས་རིང",
        "Temperature (Minimum)": "ཁྱོགས་འཚོལ། (ཨམུ་མ།)",
        "Temperature (Maximum)": "ཁྱོགས་འཚོལ། (ཨམུ་མ།)"
    },
    "tr_TR": {
        "Weather:": "Hava durumu:",
        "Your community": "Topluluğunuz",
        "Find": "Bul",
        "Add": "Ekle",
        "Currency:": "Para birimi:",
        "Your money": "Paranız",
        "Result: ": "Sonuç:",
        "Translate": "Çeviri",
        "About": "Hakkında",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Haberler\nSürüm: 1.0.0\nŞirket: OrgInfoTech",
        "Weather today: ": "Bugünkü hava durumu:",
        "Weather tomorrow: ": "Yarınki hava durumu:",
        "Go to news": "Haberlere git",
        "No news articles available": "Hiç haber makalesi mevcut değil",
        "Failed to fetch news. Please try again later": "Haber alınamadı. Lütfen daha sonra tekrar deneyin",
        "Converted amount:": "Dönüştürülen miktar:",
        "In community": "Topluluktan",
        "Today": "Bugün",
        "Tomorrow": "Yarın",
        "Clouds": "Bulutlar",
        "Pressure": "Basınç",
        "Visibility": "Görüş mesafesi",
        "Temperature (Minimum)": "Sıcaklık (minimum)",
        "Temperature (Maximum)": "Sıcaklık (maksimum)"
    },
    "tk_TM": {
        "Weather:": "Howa:",
        "Your community": "Toplumy",
        "Find": "Tap",
        "Add": "Goş",
        "Currency:": "Pul birligi:",
        "Your money": "Puluňyz",
        "Result: ": "Netije:",
        "Translate": "Terjime et",
        "About": "Barada",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Täzelikler\nWersiýa: 1.0.0\nKompaniýa: OrgInfoTech",
        "Weather today: ": "Bugünki howa:",
        "Weather tomorrow: ": "Ertirki howa:",
        "Go to news": "Täzeliklere git",
        "No news articles available": "Habar makalasy yok",
        "Failed to fetch news. Please try again later": "Habar alnanok. Soňrak gaýtadan barlaň",
        "Converted amount:": "Çalşyrylan mukdary:",
        "In community": "Toplumda",
        "Today": "Bugün",
        "Tomorrow": "Ertir",
        "Clouds": "Bulutlar",
        "Pressure": "Basyş",
        "Visibility": "Görünme",
        "Temperature (Minimum)": "Temperatura (minimum)",
        "Temperature (Maximum)": "Temperatura (maksimum)"
    },
    "uk_UA": {
        "Weather:": "Погода:",
        "Your community": "Ваша спільнота",
        "Find": "Знайти",
        "Add": "Додати",
        "Currency:": "Валюта:",
        "Your money": "Ваші гроші",
        "Result: ": "Результат:",
        "Translate": "Перекласти",
        "About": "Про нас",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Новини\nВерсія: 1.0.0\nКомпанія: OrgInfoTech",
        "Weather today: ": "Сьогоднішня погода:",
        "Weather tomorrow: ": "Завтрашня погода:",
        "Go to news": "Перейти до новин",
        "No news articles available": "Статті новин відсутні",
        "Failed to fetch news. Please try again later": "Не вдалося отримати новини. Будь ласка, спробуйте пізніше",
        "Converted amount:": "Конвертована сума:",
        "In community": "У спільноті",
        "Today": "Сьогодні",
        "Tomorrow": "Завтра",
        "Clouds": "Хмари",
        "Pressure": "Тиск",
        "Visibility": "Видимість",
        "Temperature (Minimum)": "Температура (мінімум)",
        "Temperature (Maximum)": "Температура (максимум)"
    },
    "ur_PK": {
        "Weather:": "موسم:",
        "Your community": "آپ کی کمیونٹی",
        "Find": "تلاش کریں",
        "Add": "شامل کریں",
        "Currency:": "کرنسی:",
        "Your money": "آپ کے پیسے",
        "Result: ": "نتیجہ:",
        "Translate": "ترجمہ کریں",
        "About": "کے بارے میں",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "خبریں\nورژن: 1.0.0\nکمپنی: OrgInfoTech",
        "Weather today: ": "آج کا موسم:",
        "Weather tomorrow: ": "کل کا موسم:",
        "Go to news": "خبروں پر جائیں",
        "No news articles available": "کوئی خبری مضمون دستیاب نہیں ہے",
        "Failed to fetch news. Please try again later": "خبریں حاصل کرنے میں ناکام۔ براہ کرم بعد میں دوبارہ کوشش کریں",
        "Converted amount:": "بدلا ہوا رقم:",
        "In community": "کمیونٹی میں",
        "Today": "آج",
        "Tomorrow": "کل",
        "Clouds": "بادل",
        "Pressure": "دباؤ",
        "Visibility": "دیکھنے کی صلاحیت",
        "Temperature (Minimum)": "درجہ حرارت (کم سے کم)",
        "Temperature (Maximum)": "درجہ حرارت (زیادہ سے زیادہ)"
    },
    "ug_CN": {
        "Weather:": "ھەۋا رايى:",
        "Your community": "سېزنىڭ جامائىتىڭىز",
        "Find": "تەپتىرگۈچ",
        "Add": "قوشۇش",
        "Currency:": "پۇل بىرىكتىرىشى:",
        "Your money": "سېزنىڭ پۇلۇڭىز",
        "Result: ": "نەتىجە:",
        "Translate": "تەرجىمە",
        "About": "تۇرۇندە",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "خەۋەر\nنىشان: 1.0.0\nكومپانىيە: OrgInfoTech",
        "Weather today: ": "بۈگۈنكى ھەۋا رايى:",
        "Weather tomorrow: ": "ئەتەكى ھەۋا رايى:",
        "Go to news": "خەۋەرگە كىرىڭ",
        "No news articles available": "خەۋەر مەقالەسى يوق",
        "Failed to fetch news. Please try again later": "خەۋەرنى ئوقۇشقا ئۇچرىشىشقا چەكتەندە. تېخىمۇ يەنە قەدەم قەدەم بىر ھېس قۇيۇم تەكرارلىسىڭىز",
        "Converted amount:": "ئالماشتۇرۇلغان سومما:",
        "In community": "جامائىتتا",
        "Today": "بۈگۈن",
        "Tomorrow": "ئەتە",
        "Clouds": "بولۇت",
        "Pressure": "باسىم",
        "Visibility": "كۆرۈنۈش",
        "Temperature (Minimum)": "ھارارەت (ئەڭ ئاز)",
        "Temperature (Maximum)": "ھارارەت (ئەڭ يۇقىرى)"
    },
    "uz_UZ": {
        "Weather:": "Havo:",
        "Your community": "Jamoangiz",
        "Find": "Toping",
        "Add": "Qo'shing",
        "Currency:": "Valyuta:",
        "Your money": "Puliz",
        "Result: ": "Natija:",
        "Translate": "Tarjima",
        "About": "Haqida",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Yangiliklar\nVersiya: 1.0.0\nKompaniya: OrgInfoTech",
        "Weather today: ": "Bugungi ob-havo:",
        "Weather tomorrow: ": "Ertangi ob-havo:",
        "Go to news": "Yangiliklarga o'ting",
        "No news articles available": "Yangilik maqolalari mavjud emas",
        "Failed to fetch news. Please try again later": "Yangilik olish muvaffaqiyatsiz. Iltimos keyinroq yana urinib ko'ring",
        "Converted amount:": "O'zgartirilgan miqdor:",
        "In community": "Jamoatda",
        "Today": "Bugun",
        "Tomorrow": "Ertaga",
        "Clouds": "Bulutlar",
        "Pressure": "Bosim",
        "Visibility": "Ko'rinish",
        "Temperature (Minimum)": "Harorat (minimal)",
        "Temperature (Maximum)": "Harorat (maksimal)"
    },
    "vi_VN": {
        "Weather:": "Thời tiết:",
        "Your community": "Cộng đồng của bạn",
        "Find": "Tìm kiếm",
        "Add": "Thêm",
        "Currency:": "Tiền tệ:",
        "Your money": "Tiền của bạn",
        "Result: ": "Kết quả:",
        "Translate": "Dịch",
        "About": "Về",
        "News\nVersion: 1.0.0\nCompany: OrgInfoTech": "Tin tức\nPhiên bản: 1.0.0\nCông ty: OrgInfoTech",
        "Weather today: ": "Thời tiết hôm nay:",
        "Weather tomorrow: ": "Thời tiết ngày mai:",
        "Go to news": "Đến tin tức",
        "No news articles available": "Không có bài viết tin tức nào",
        "Failed to fetch news. Please try again later": "Không thể tải tin tức. Vui lòng thử lại sau",
        "Converted amount:": "Số tiền đã chuyển đổi:",
        "In community": "Trong cộng đồng",
        "Today": "Hôm nay",
        "Tomorrow": "Ngày mai",
        "Clouds": "Mây",
        "Pressure": "Áp suất",
        "Visibility": "Tầm nhìn",
        "Temperature (Minimum)": "Nhiệt độ (Tối thiểu)",
        "Temperature (Maximum)": "Nhiệt độ (Tối đa)"
    }
}