langDict = {
    "ar_SA":{
        "Home":"الصفحة الرئيسية",
        "Updating":"التحديث",
        "Remote connection":"الاتصال عن بعد",
        "About":"حول",
        "Welcome to Dashboard":"مرحبا بك في لوحة التحكم",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"لوحة القيادة\nالمؤلف: OrgInfoTech @2024\nالإصدار: 1.0.0 (01/01/2024)",
        "Update packages":"تحديث الحزم",
        "Downloads updates":"تنزيل التحديثات",
        "To do all":"للقيام بكل شيء",
        "Checking ...":"جاري الفحص...",
        "You should to install updates for your PC":"يجب عليك تثبيت التحديثات لجهاز الكمبيوتر الخاص بك",
        "Finding of updates was failed":"فشل العثور على التحديثات",
        "IP of PC":"عنوان IP لجهاز الكمبيوتر",
        "Your IP":"عنوان IP الخاص بك",
        "Connect":"اتصال",
        "How to use \nDashboard?":"كيفية استخدام \nلوحة التحكم؟",
        "What new \nin SerOS?":"ما الجديد \nفي SerOS؟",
        "Your PC isn't needing to update now":"جهاز الكمبيوتر الخاص بك لا يحتاج إلى تحديث الآن",
        "User of PC":"مستخدم جهاز الكمبيوتر",
        "Open a program in PC":"فتح برنامج في جهاز الكمبيوتر",
        "Add": "إضافة",
        "Remove": "إزالة",
        "Open": "فتح",
        "Play": "تشغيل",
        "Stop": "توقف",
        "List": "قائمة"
    },
    "hy_AM":{
        "Home":"Գլխավոր էջ",
        "Updating":"Թարմացում",
        "Remote connection":"Հեռակա կապ",
        "About":"Մասին",
        "Welcome to Dashboard":"Բարի գալուստ Վահանակ",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Վահանակ\nԵրաժշտություն: OrgInfoTech @2024\nՎերսիա: 1.0.0 (01/01/2024)",
        "Update packages":"Թարմացնել փաթեթները",
        "Downloads updates":"Ներբեռնել թարմացումները",
        "To do all":"Անել ամեն ինչ",
        "Checking ...":"Ստուգում է...",
        "You should to install updates for your PC":"Դուք պետք է տեղադրեք թարմացումներ ձեր համակարգչի համար",
        "Finding of updates was failed":"Թարմացումների որոնումը ձախողվեց",
        "IP of PC":"Համակարգչի IP հասցեն",
        "Your IP":"Ձեր IP հասցեն",
        "Connect":"Միանալ",
        "How to use \nDashboard?":"Ինչպես օգտագործել \nVahanak?",
        "What new \nin SerOS?":"Ինչ նոր \nSerOS-ում?",
        "Your PC isn't needing to update now":"Ձեր համակարգչին հիմա թարմացում չի պահանջվում",
        "User of PC":"Համակարգչի օգտագործող",
        "Open a program in PC":"Բացել ծրագիր համակարգչում",
        "Add": "Ավելացնել",
        "Remove": "Հեռացնել",
        "Open": "Բացել",
        "Play": "Համարձակել",
        "Stop": "Դադարեցնել",
        "List": "Ցուցակ"
    },
    "az_AZ":{
        "Home":"Ana səhifə",
        "Updating":"Yeniləmə",
        "Remote connection":"Uzaqdan qoşulma",
        "About":"Haqqında",
        "Welcome to Dashboard":"İdarə panelinə xoş gəldiniz",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"İdarə paneli\nMüəllif: OrgInfoTech @2024\nVersiya: 1.0.0 (01/01/2024)",
        "Update packages":"Paketləri yenilə",
        "Downloads updates":"Yeniləmələri yüklə",
        "To do all":"Hər şeyi etmək",
        "Checking ...":"Yoxlanılır...",
        "You should to install updates for your PC":"PC-niz üçün yeniləmələri quraşdırmaq lazımdır",
        "Finding of updates was failed":"Yeniləmələrin tapılması uğursuz oldu",
        "IP of PC":"PC-nin IP ünvanı",
        "Your IP":"Sizin IP-niz",
        "Connect":"Qoşulmaq",
        "How to use \nDashboard?":"İdarə panelindən necə istifadə edə bilərəm?",
        "What new \nin SerOS?":"SerOS-da nə yeni var?",
        "Your PC isn't needing to update now":"Sizin PC-niz indi yeniləməyə ehtiyacı yoxdur",
        "User of PC":"PC istifadəçisi",
        "Open a program in PC":"PC-də proqramı aç",
        "Add": "Əlavə et",
        "Remove": "Sil",
        "Open": "Aç",
        "Play": "Oynat",
        "Stop": "Dayandır",
        "List": "Siyahı"
    },
    "bg_BG":{
        "Home":"Начало",
        "Updating":"Актуализация",
        "Remote connection":"Отдалечена връзка",
        "About":"Относно",
        "Welcome to Dashboard":"Добре дошли в контролната табла",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Контролната табла\nАвтор: OrgInfoTech @2024\nВерсия: 1.0.0 (01/01/2024)",
        "Update packages":"Актуализиране на пакетите",
        "Downloads updates":"Изтегляне на актуализации",
        "To do all":"За да направите всичко",
        "Checking ...":"Проверка...",
        "You should to install updates for your PC":"Трябва да инсталирате актуализации за вашия компютър",
        "Finding of updates was failed":"Неуспешно намиране на актуализации",
        "IP of PC":"IP на компютъра",
        "Your IP":"Вашият IP",
        "Connect":"Свързване",
        "How to use \nDashboard?":"Как да използвате контролната табла?",
        "What new \nin SerOS?":"Какво ново в SerOS?",
        "Your PC isn't needing to update now":"Вашият компютър в момента не се нуждае от актуализация",
        "User of PC":"Потребител на компютъра",
        "Open a program in PC":"Отваряне на програма в компютъра",
        "Add": "Добави",
        "Remove": "Премахни",
        "Open": "Отвори",
        "Play": "Пусни",
        "Stop": "Спри",
        "List": "Списък"
    },
    "zh_CN":{
        "Home":"主页",
        "Updating":"更新",
        "Remote connection":"远程连接",
        "About":"关于",
        "Welcome to Dashboard":"欢迎来到仪表板",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"仪表板\n作者: OrgInfoTech @2024\n版本: 1.0.0 (01/01/2024)",
        "Update packages":"更新软件包",
        "Downloads updates":"下载更新",
        "To do all":"执行所有操作",
        "Checking ...":"检查中...",
        "You should to install updates for your PC":"您应该为您的计算机安装更新",
        "Finding of updates was failed":"未能找到更新",
        "IP of PC":"计算机IP",
        "Your IP":"您的IP",
        "Connect":"连接",
        "How to use \nDashboard?":"如何使用仪表板？",
        "What new \nin SerOS?":"SerOS有什么新功能？",
        "Your PC isn't needing to update now":"您的计算机现在不需要更新",
        "User of PC":"计算机用户",
        "Open a program in PC":"在计算机中打开程序",
        "Add": "添加",
        "Remove": "移除",
        "Open": "打开",
        "Play": "播放",
        "Stop": "停止",
        "List": "列表"
    },
    "zh_TW":{
        "Home":"首頁",
        "Updating":"更新中",
        "Remote connection":"遠端連線",
        "About":"關於",
        "Welcome to Dashboard":"歡迎來到儀表板",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"儀表板\n作者: OrgInfoTech @2024\n版本: 1.0.0 (01/01/2024)",
        "Update packages":"更新套件",
        "Downloads updates":"下載更新",
        "To do all":"進行所有操作",
        "Checking ...":"檢查中...",
        "You should to install updates for your PC":"您應該為您的電腦安裝更新",
        "Finding of updates was failed":"找不到更新",
        "IP of PC":"電腦IP",
        "Your IP":"您的IP",
        "Connect":"連線",
        "How to use \nDashboard?":"如何使用儀表板？",
        "What new \nin SerOS?":"SerOS有什麼新功能？",
        "Your PC isn't needing to update now":"您的電腦目前不需要更新",
        "User of PC":"電腦使用者",
        "Open a program in PC":"在電腦上開啟程式",
        "Add": "新增",
        "Remove": "移除",
        "Open": "開啟",
        "Play": "播放",
        "Stop": "停止",
        "List": "清單"
    },
    "hr_HR":{
        "Home":"Početna",
        "Updating":"Ažuriranje",
        "Remote connection":"Udaljena veza",
        "About":"O nama",
        "Welcome to Dashboard":"Dobrodošli na nadzornu ploču",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Nadzorna ploča\nAutor: OrgInfoTech @2024\nVerzija: 1.0.0 (01/01/2024)",
        "Update packages":"Ažuriraj pakete",
        "Downloads updates":"Preuzmi ažuriranja",
        "To do all":"Obaviti sve",
        "Checking ...":"Provjerava se...",
        "You should to install updates for your PC":"Trebate instalirati ažuriranja za svoje računalo",
        "Finding of updates was failed":"Pronalaženje ažuriranja nije uspjelo",
        "IP of PC":"IP adresa računala",
        "Your IP":"Vaša IP adresa",
        "Connect":"Spoji se",
        "How to use \nDashboard?":"Kako koristiti nadzornu ploču?",
        "What new \nin SerOS?":"Što je novo u SerOS-u?",
        "Your PC isn't needing to update now":"Vaše računalo trenutno ne treba ažuriranje",
        "User of PC":"Korisnik računala",
        "Open a program in PC":"Otvori program na računalu",
        "Add": "Dodaj",
        "Remove": "Ukloni",
        "Open": "Otvori",
        "Play": "Reproduciraj",
        "Stop": "Zaustavi",
        "List": "Popis"
    },
    "cs_CZ":{
        "Home":"Domů",
        "Updating":"Aktualizace",
        "Remote connection":"Vzdálené připojení",
        "About":"O aplikaci",
        "Welcome to Dashboard":"Vítejte na nástěnce",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Nástěnka\nAutor: OrgInfoTech @2024\nVerze: 1.0.0 (01/01/2024)",
        "Update packages":"Aktualizovat balíčky",
        "Downloads updates":"Stáhnout aktualizace",
        "To do all":"Provést vše",
        "Checking ...":"Kontrola...",
        "You should to install updates for your PC":"Měli byste nainstalovat aktualizace pro váš počítač",
        "Finding of updates was failed":"Nepodařilo se najít aktualizace",
        "IP of PC":"IP adresa počítače",
        "Your IP":"Vaše IP adresa",
        "Connect":"Připojit",
        "How to use \nDashboard?":"Jak používat nástěnku?",
        "What new \nin SerOS?":"Co je nového v SerOS?",
        "Your PC isn't needing to update now":"Váš počítač v tuto chvíli nepotřebuje aktualizaci",
        "User of PC":"Uživatel počítače",
        "Open a program in PC":"Otevřít program v počítači",
        "Add": "Přidat",
        "Remove": "Odebrat",
        "Open": "Otevřít",
        "Play": "Přehrát",
        "Stop": "Zastavit",
        "List": "Seznam"
    },
    "da_DK":{
        "Home":"Hjem",
        "Updating":"Opdatering",
        "Remote connection":"Fjernforbindelse",
        "About":"Om",
        "Welcome to Dashboard":"Velkommen til kontrolpanelet",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Kontrolpanel\nForfatter: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)",
        "Update packages":"Opdater pakker",
        "Downloads updates":"Hent opdateringer",
        "To do all":"Udfør alle",
        "Checking ...":"Kontrollerer...",
        "You should to install updates for your PC":"Du bør installere opdateringer til din computer",
        "Finding of updates was failed":"Søgning efter opdateringer mislykkedes",
        "IP of PC":"PC's IP",
        "Your IP":"Din IP",
        "Connect":"Forbind",
        "How to use \nDashboard?":"Hvordan bruger du kontrolpanelet?",
        "What new \nin SerOS?":"Hvad er nyt i SerOS?",
        "Your PC isn't needing to update now":"Din computer behøver ikke opdatering lige nu",
        "User of PC":"Bruger af computer",
        "Open a program in PC":"Åbn et program på computeren",
        "Add": "Tilføj",
        "Remove": "Fjern",
        "Open": "Åbn",
        "Play": "Afspil",
        "Stop": "Stop",
        "List": "Liste"
    },
    "nl_NL":{
        "Home":"Home",
        "Updating":"Bijwerken",
        "Remote connection":"Externe verbinding",
        "About":"Over",
        "Welcome to Dashboard":"Welkom bij het dashboard",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Dashboard\nAuteur: OrgInfoTech @2024\nVersie: 1.0.0 (01/01/2024)",
        "Update packages":"Pakketten bijwerken",
        "Downloads updates":"Updates downloaden",
        "To do all":"Alles uitvoeren",
        "Checking ...":"Controleren...",
        "You should to install updates for your PC":"U moet updates installeren voor uw computer",
        "Finding of updates was failed":"Het vinden van updates is mislukt",
        "IP of PC":"IP van de computer",
        "Your IP":"Uw IP",
        "Connect":"Verbinden",
        "How to use \nDashboard?":"Hoe gebruik je het dashboard?",
        "What new \nin SerOS?":"Wat is er nieuw in SerOS?",
        "Your PC isn't needing to update now":"Uw computer heeft nu geen update nodig",
        "User of PC":"Gebruiker van de computer",
        "Open a program in PC":"Een programma openen op de computer",
        "Add": "Toevoegen",
        "Remove": "Verwijderen",
        "Open": "Openen",
        "Play": "Afspelen",
        "Stop": "Stoppen",
        "List": "Lijst"
    },
    "en_US":{
        "Home":"Home",
        "Updating":"Updating",
        "Remote connection":"Remote connection",
        "About":"About",
        "Welcome to Dashboard":"Welcome to Dashboard",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)",
        "Update packages":"Update packages",
        "Downloads updates":"Downloads updates",
        "To do all":"To do all",
        "Checking ...":"Checking ...",
        "You should to install updates for your PC":"You should to install updates for your PC",
        "Finding of updates was failed":"Finding of updates was failed",
        "IP of PC":"IP of PC",
        "Your IP":"Your IP",
        "Connect":"Connect",
        "How to use \nDashboard?":"How to use \nDashboard?",
        "What new \nin SerOS?":"What new \nin SerOS?",
        "Your PC isn't needing to update now":"Your PC isn't needing to update now",
        "User of PC":"User of PC",
        "Open a program in PC":"Open a program in PC",
        "Add":"Add",
        "Remove":"Remove",
        "Open":"Open",
        "Play":"Play",
        "Stop":"Stop",
        "List":"List"
    },
    "en_GB":{
        "Home":"Home",
        "Updating":"Updating",
        "Remote connection":"Remote connection",
        "About":"About",
        "Welcome to Dashboard":"Welcome to Dashboard",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)",
        "Update packages":"Update packages",
        "Downloads updates":"Downloads updates",
        "To do all":"To do all",
        "Checking ...":"Checking ...",
        "You should to install updates for your PC":"You should to install updates for your PC",
        "Finding of updates was failed":"Finding of updates was failed",
        "IP of PC":"IP of PC",
        "Your IP":"Your IP",
        "Connect":"Connect",
        "How to use \nDashboard?":"How to use \nDashboard?",
        "What new \nin SerOS?":"What new \nin SerOS?",
        "Your PC isn't needing to update now":"Your PC isn't needing to update now",
        "User of PC":"User of PC",
        "Open a program in PC":"Open a program in PC",
        "Add":"Add",
        "Remove":"Remove",
        "Open":"Open",
        "Play":"Play",
        "Stop":"Stop",
        "List":"List"
    },
    "en_CA":{
        "Home":"Home",
        "Updating":"Updating",
        "Remote connection":"Remote connection",
        "About":"About",
        "Welcome to Dashboard":"Welcome to Dashboard",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)",
        "Update packages":"Update packages",
        "Downloads updates":"Downloads updates",
        "To do all":"To do all",
        "Checking ...":"Checking ...",
        "You should to install updates for your PC":"You should to install updates for your PC",
        "Finding of updates was failed":"Finding of updates was failed",
        "IP of PC":"IP of PC",
        "Your IP":"Your IP",
        "Connect":"Connect",
        "How to use \nDashboard?":"How to use \nDashboard?",
        "What new \nin SerOS?":"What new \nin SerOS?",
        "Your PC isn't needing to update now":"Your PC isn't needing to update now",
        "User of PC":"User of PC",
        "Open a program in PC":"Open a program in PC",
        "Add":"Add",
        "Remove":"Remove",
        "Open":"Open",
        "Play":"Play",
        "Stop":"Stop",
        "List":"List"
    },
    "en_AU":{
        "Home":"Home",
        "Updating":"Updating",
        "Remote connection":"Remote connection",
        "About":"About",
        "Welcome to Dashboard":"Welcome to Dashboard",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)",
        "Update packages":"Update packages",
        "Downloads updates":"Downloads updates",
        "To do all":"To do all",
        "Checking ...":"Checking ...",
        "You should to install updates for your PC":"You should to install updates for your PC",
        "Finding of updates was failed":"Finding of updates was failed",
        "IP of PC":"IP of PC",
        "Your IP":"Your IP",
        "Connect":"Connect",
        "How to use \nDashboard?":"How to use \nDashboard?",
        "What new \nin SerOS?":"What new \nin SerOS?",
        "Your PC isn't needing to update now":"Your PC isn't needing to update now",
        "User of PC":"User of PC",
        "Open a program in PC":"Open a program in PC",
        "Add":"Add",
        "Remove":"Remove",
        "Open":"Open",
        "Play":"Play",
        "Stop":"Stop",
        "List":"List"
    },
    "et_EE":{
        "Home":"Avaleht",
        "Updating":"Uuendamine",
        "Remote connection":"Kaugühendus",
        "About":"Info",
        "Welcome to Dashboard":"Tere tulemast juhtpaneelile",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Juhtpaneel\nAutor: OrgInfoTech @2024\nVersioon: 1.0.0 (01/01/2024)",
        "Update packages":"Uuenda pakette",
        "Downloads updates":"Laadi uuendused alla",
        "To do all":"Tee kõik",
        "Checking ...":"Kontrollimine...",
        "You should to install updates for your PC":"Peaksite oma arvutisse installima uuendused",
        "Finding of updates was failed":"Uuenduste leidmine ebaõnnestus",
        "IP of PC":"Arvuti IP",
        "Your IP":"Teie IP",
        "Connect":"Ühenda",
        "How to use \nDashboard?":"Kuidas kasutada juhtpaneeli?",
        "What new \nin SerOS?":"Mis on uut SerOS-is?",
        "Your PC isn't needing to update now":"Teie arvuti ei vaja hetkel uuendamist",
        "User of PC":"Arvuti kasutaja",
        "Open a program in PC":"Ava programm arvutis",
        "Add": "Lisa",
        "Remove": "Eemalda",
        "Open": "Ava",
        "Play": "Mängi",
        "Stop": "Stopp",
        "List": "Nimekiri"
    },
    "fi_FI":{
        "Home":"Koti",
        "Updating":"Päivittäminen",
        "Remote connection":"Etäyhteys",
        "About":"Tietoja",
        "Welcome to Dashboard":"Tervetuloa ohjauspaneeliin",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Ohjauspaneeli\nTekijä: OrgInfoTech @2024\nVersio: 1.0.0 (01/01/2024)",
        "Update packages":"Päivitä paketit",
        "Downloads updates":"Lataa päivitykset",
        "To do all":"Tee kaikki",
        "Checking ...":"Tarkistetaan...",
        "You should to install updates for your PC":"Sinun pitäisi asentaa päivitykset tietokoneeseen",
        "Finding of updates was failed":"Päivitysten etsiminen epäonnistui",
        "IP of PC":"Tietokoneen IP",
        "Your IP":"Sinun IP",
        "Connect":"Yhdistä",
        "How to use \nDashboard?":"Kuinka käyttää ohjauspaneelia?",
        "What new \nin SerOS?":"Mitä uutta SerOS:ssa?",
        "Your PC isn't needing to update now":"Tietokoneesi ei tarvitse päivitystä tällä hetkellä",
        "User of PC":"Tietokoneen käyttäjä",
        "Open a program in PC":"Avaa ohjelma tietokoneessa",
        "Add": "Lisää",
        "Remove": "Poista",
        "Open": "Avaa",
        "Play": "Toista",
        "Stop": "Pysäytä",
        "List": "Lista"
    },
    "fr_FR":{
        "Home":"Accueil",
        "Updating":"Mise à jour",
        "Remote connection":"Connexion à distance",
        "About":"À propos",
        "Welcome to Dashboard":"Bienvenue sur le tableau de bord",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Tableau de bord\nAuteur: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)",
        "Update packages":"Mettre à jour les paquets",
        "Downloads updates":"Télécharger les mises à jour",
        "To do all":"Faire tout",
        "Checking ...":"Vérification en cours...",
        "You should to install updates for your PC":"Vous devriez installer des mises à jour pour votre ordinateur",
        "Finding of updates was failed":"La recherche de mises à jour a échoué",
        "IP of PC":"Adresse IP de l'ordinateur",
        "Your IP":"Votre adresse IP",
        "Connect":"Se connecter",
        "How to use \nDashboard?":"Comment utiliser le tableau de bord?",
        "What new \nin SerOS?":"Quoi de nouveau dans SerOS?",
        "Your PC isn't needing to update now":"Votre ordinateur n'a pas besoin de mise à jour pour l'instant",
        "User of PC":"Utilisateur de l'ordinateur",
        "Open a program in PC":"Ouvrir un programme sur l'ordinateur",
        "Add": "Ajouter",
        "Remove": "Supprimer",
        "Open": "Ouvrir",
        "Play": "Jouer",
        "Stop": "Arrêter",
        "List": "Liste"
    },
    "fr_CA":{
        "Home":"Accueil",
        "Updating":"Mise à jour",
        "Remote connection":"Connexion à distance",
        "About":"À propos",
        "Welcome to Dashboard":"Bienvenue sur le tableau de bord",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Tableau de bord\nAuteur: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)",
        "Update packages":"Mettre à jour les paquets",
        "Downloads updates":"Télécharger les mises à jour",
        "To do all":"Faire tout",
        "Checking ...":"Vérification en cours...",
        "You should to install updates for your PC":"Vous devriez installer des mises à jour pour votre ordinateur",
        "Finding of updates was failed":"La recherche de mises à jour a échoué",
        "IP of PC":"Adresse IP de l'ordinateur",
        "Your IP":"Votre adresse IP",
        "Connect":"Se connecter",
        "How to use \nDashboard?":"Comment utiliser le tableau de bord?",
        "What new \nin SerOS?":"Quoi de nouveau dans SerOS?",
        "Your PC isn't needing to update now":"Votre ordinateur n'a pas besoin de mise à jour pour l'instant",
        "User of PC":"Utilisateur de l'ordinateur",
        "Open a program in PC":"Ouvrir un programme sur l'ordinateur",
        "Add": "Ajouter",
        "Remove": "Retirer",
        "Open": "Ouvrir",
        "Play": "Jouer",
        "Stop": "Arrêter",
        "List": "Liste"
    },
    "ka_GE":{
        "Home":"მთავარი",
        "Updating":"განახლება",
        "Remote connection":"დისტანციური კავშირი",
        "About":"შესახებ",
        "Welcome to Dashboard":"კონტროლურ პანელში მოგესალმებით",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"პანელი\nავტორი: OrgInfoTech @2024\nვერსია: 1.0.0 (01/01/2024)",
        "Update packages":"პაკეტების განახლება",
        "Downloads updates":"განახლებების ჩამოტვირთვა",
        "To do all":"ყველას შესრულება",
        "Checking ...":"შემოწმება...",
        "You should to install updates for your PC":"თქვენ უნდა დააყენოთ განახლებები თქვენი კომპიუტერისთვის",
        "Finding of updates was failed":"განახლებების პოვნა ჩაიშლა",
        "IP of PC":"კომპიუტერის IP",
        "Your IP":"თქვენი IP",
        "Connect":"დაკავშირება",
        "How to use \nDashboard?":"როგორ გამოიყენოთ პანელი?",
        "What new \nin SerOS?":"რა ახალია SerOS-ში?",
        "Your PC isn't needing to update now":"თქვენი კომპიუტერი ამჟამად არ სჭირდება განახლება",
        "User of PC":"კომპიუტერის მომხმარე",
        "Open a program in PC":"პროგრამას გახსნა კომპიუტერში",
        "Add": "დამატება",
        "Remove": "წაშლა",
        "Open": "გახსნა",
        "Play": "დაიწყე",
        "Stop": "შეჩერება",
        "List": "სია"
    },
    "de_DE":{
        "Home":"Startseite",
        "Updating":"Aktualisierung",
        "Remote connection":"Remote-Verbindung",
        "About":"Über",
        "Welcome to Dashboard":"Willkommen im Dashboard",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Dashboard\nAutor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)",
        "Update packages":"Pakete aktualisieren",
        "Downloads updates":"Updates herunterladen",
        "To do all":"Alles erledigen",
        "Checking ...":"Überprüfung läuft...",
        "You should to install updates for your PC":"Sie sollten Updates für Ihren PC installieren",
        "Finding of updates was failed":"Suche nach Updates fehlgeschlagen",
        "IP of PC":"IP des PCs",
        "Your IP":"Ihre IP",
        "Connect":"Verbinden",
        "How to use \nDashboard?":"Wie benutzt man das Dashboard?",
        "What new \nin SerOS?":"Was ist neu in SerOS?",
        "Your PC isn't needing to update now":"Ihr PC benötigt derzeit keine Aktualisierung",
        "User of PC":"Benutzer des PCs",
        "Open a program in PC":"Ein Programm auf dem PC öffnen",
        "Add": "Hinzufügen",
        "Remove": "Entfernen",
        "Open": "Öffnen",
        "Play": "Abspielen",
        "Stop": "Stopp",
        "List": "Liste"
    },
    "el_GR":{
        "Home":"Αρχική",
        "Updating":"Ενημέρωση",
        "Remote connection":"Απομακρυσμένη σύνδεση",
        "About":"Σχετικά",
        "Welcome to Dashboard":"Καλώς ήρθατε στον πίνακα ελέγχου",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Πίνακας ελέγχου\nΣυγγραφέας: OrgInfoTech @2024\nΈκδοση: 1.0.0 (01/01/2024)",
        "Update packages":"Ενημέρωση πακέτων",
        "Downloads updates":"Λήψη ενημερώσεων",
        "To do all":"Εκτέλεση όλων",
        "Checking ...":"Έλεγχος...",
        "You should to install updates for your PC":"Θα πρέπει να εγκαταστήσετε ενημερώσεις για τον υπολογιστή σας",
        "Finding of updates was failed":"Η αναζήτηση ενημερώσεων απέτυχε",
        "IP of PC":"IP υπολογιστή",
        "Your IP":"Το IP σας",
        "Connect":"Σύνδεση",
        "How to use \nDashboard?":"Πώς να χρησιμοποιήσετε τον πίνακα ελέγχου;",
        "What new \nin SerOS?":"Τι νέο υπάρχει στο SerOS;",
        "Your PC isn't needing to update now":"Ο υπολογιστής σας δεν χρειάζεται ενημέρωση αυτή τη στιγμή",
        "User of PC":"Χρήστης υπολογιστή",
        "Open a program in PC":"Άνοιγμα προγράμματος στον υπολογιστή",
        "Add": "Προσθήκη",
        "Remove": "Αφαίρεση",
        "Open": "Άνοιγμα",
        "Play": "Αναπαραγωγή",
        "Stop": "Διακοπή",
        "List": "Λίστα"
    },
    "he_IL":{
        "Home":"בית",
        "Updating":"עדכון",
        "Remote connection":"חיבור מרחוק",
        "About":"אודות",
        "Welcome to Dashboard":"ברוכים הבאים ללוח הבקרה",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"לוח בקרה\nמחבר: OrgInfoTech @2024\nגרסה: 1.0.0 (01/01/2024)",
        "Update packages":"עדכון חבילות",
        "Downloads updates":"הורדת עדכונים",
        "To do all":"לבצע הכל",
        "Checking ...":"בודק...",
        "You should to install updates for your PC":"עליך להתקין עדכונים למחשב שלך",
        "Finding of updates was failed":"חיפוש העדכונים נכשל",
        "IP of PC":"כתובת ה-IP של המחשב",
        "Your IP":"כתובת ה-IP שלך",
        "Connect":"התחבר",
        "How to use \nDashboard?":"איך להשתמש בלוח הבקרה?",
        "What new \nin SerOS?":"מה חדש ב-SerOS?",
        "Your PC isn't needing to update now":"המחשב שלך אינו זקוק לעדכון כרגע",
        "User of PC":"משתמש במחשב",
        "Open a program in PC":"פתיחת תוכנית במחשב",
        "Add": "הוסף",
        "Remove": "הסר",
        "Open": "פתח",
        "Play": "נגן",
        "Stop": "עצור",
        "List": "רשימה"
    },
    "hi_IN":{
        "Home":"मुख्य पृष्ठ",
        "Updating":"अपडेट करना",
        "Remote connection":"दूरस्थ कनेक्शन",
        "About":"के बारे में",
        "Welcome to Dashboard":"डैशबोर्ड में आपका स्वागत है",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"डैशबोर्ड\nलेखक: OrgInfoTech @2024\nसंस्करण: 1.0.0 (01/01/2024)",
        "Update packages":"पैकेज अपडेट करें",
        "Downloads updates":"अपडेट डाउनलोड करें",
        "To do all":"सब कुछ करने के लिए",
        "Checking ...":"जांच कर रहा है...",
        "You should to install updates for your PC":"आपको अपने PC के लिए अपडेट इंस्टॉल करने चाहिए",
        "Finding of updates was failed":"अपडेट खोजने में विफल",
        "IP of PC":"PC का IP",
        "Your IP":"आपका IP",
        "Connect":"कनेक्ट करें",
        "How to use \nDashboard?":"डैशबोर्ड का उपयोग कैसे करें?",
        "What new \nin SerOS?":"SerOS में क्या नया है?",
        "Your PC isn't needing to update now":"आपका PC अभी अपडेट की जरूरत नहीं है",
        "User of PC":"PC का उपयोगकर्ता",
        "Open a program in PC":"PC में प्रोग्राम खोलें",
        "Add": "जोड़ें",
        "Remove": "हटाएं",
        "Open": "खोलें",
        "Play": "चलाएं",
        "Stop": "रोकें",
        "List": "सूची"
    },
    "hu_HU":{
        "Home":"Kezdőlap",
        "Updating":"Frissítés",
        "Remote connection":"Távoli kapcsolat",
        "About":"Névjegy",
        "Welcome to Dashboard":"Üdvözöljük a műszerfalon",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Műszerfal\nSzerző: OrgInfoTech @2024\nVerzió: 1.0.0 (01/01/2024)",
        "Update packages":"Csomagok frissítése",
        "Downloads updates":"Frissítések letöltése",
        "To do all":"Mindent elvégez",
        "Checking ...":"Ellenőrzés...",
        "You should to install updates for your PC":"Telepítenie kell a frissítéseket a számítógépére",
        "Finding of updates was failed":"A frissítések keresése sikertelen volt",
        "IP of PC":"A számítógép IP-címe",
        "Your IP":"Az Ön IP-címe",
        "Connect":"Csatlakozás",
        "How to use \nDashboard?":"Hogyan használjam a műszerfalat?",
        "What new \nin SerOS?":"Mi új a SerOS-ban?",
        "Your PC isn't needing to update now":"A számítógépének most nincs szüksége frissítésre",
        "User of PC":"A számítógép felhasználója",
        "Open a program in PC":"Program megnyitása a számítógépen",
        "Add": "Hozzáadás",
        "Remove": "Eltávolítás",
        "Open": "Megnyitás",
        "Play": "Lejátszás",
        "Stop": "Megállítás",
        "List": "Lista"
    },
    "it_IT":{
        "Home":"Home",
        "Updating":"Aggiornamento",
        "Remote connection":"Connessione remota",
        "About":"Informazioni",
        "Welcome to Dashboard":"Benvenuto nel Dashboard",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Dashboard\nAutore: OrgInfoTech @2024\nVersione: 1.0.0 (01/01/2024)",
        "Update packages":"Aggiorna pacchetti",
        "Downloads updates":"Scarica aggiornamenti",
        "To do all":"Esegui tutto",
        "Checking ...":"Verifica in corso...",
        "You should to install updates for your PC":"Dovresti installare gli aggiornamenti per il tuo PC",
        "Finding of updates was failed":"Ricerca degli aggiornamenti non riuscita",
        "IP of PC":"IP del PC",
        "Your IP":"Il tuo IP",
        "Connect":"Connetti",
        "How to use \nDashboard?":"Come usare il Dashboard?",
        "What new \nin SerOS?":"Cosa c'è di nuovo in SerOS?",
        "Your PC isn't needing to update now":"Il tuo PC non ha bisogno di aggiornamenti al momento",
        "User of PC":"Utente del PC",
        "Open a program in PC":"Apri un programma sul PC",
        "Add": "Aggiungi",
        "Remove": "Rimuovi",
        "Open": "Apri",
        "Play": "Riproduci",
        "Stop": "Stop",
        "List": "Lista"
    },
    "ja_JP":{
        "Home":"ホーム",
        "Updating":"更新",
        "Remote connection":"リモート接続",
        "About":"について",
        "Welcome to Dashboard":"ダッシュボードへようこそ",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"ダッシュボード\n作者: OrgInfoTech @2024\nバージョン: 1.0.0 (01/01/2024)",
        "Update packages":"パッケージを更新",
        "Downloads updates":"更新をダウンロード",
        "To do all":"すべて実行",
        "Checking ...":"チェック中...",
        "You should to install updates for your PC":"PCの更新をインストールする必要があります",
        "Finding of updates was failed":"更新の検索に失敗しました",
        "IP of PC":"PCのIP",
        "Your IP":"あなたのIP",
        "Connect":"接続",
        "How to use \nDashboard?":"ダッシュボードの使い方は？",
        "What new \nin SerOS?":"SerOSの新機能は？",
        "Your PC isn't needing to update now":"現在、PCの更新は必要ありません",
        "User of PC":"PCのユーザー",
        "Open a program in PC":"PCでプログラムを開く",
        "Add": "追加",
        "Remove": "削除",
        "Open": "開く",
        "Play": "再生",
        "Stop": "停止",
        "List": "リスト"
    },
    "kk_KZ":{
        "Home":"Басты бет",
        "Updating":"Жаңарту",
        "Remote connection":"Қашықтан қосылу",
        "About":"Туралы",
        "Welcome to Dashboard":"Басқару тақтасына қош келдіңіз",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Басқару тақтасы\nАвтор: OrgInfoTech @2024\nНұсқасы: 1.0.0 (01/01/2024)",
        "Update packages":"Пакеттерді жаңарту",
        "Downloads updates":"Жаңартуларды жүктеп алу",
        "To do all":"Барлығын орындау",
        "Checking ...":"Тексеру...",
        "You should to install updates for your PC":"Компьютеріңізге жаңартуларды орнатуыңыз керек",
        "Finding of updates was failed":"Жаңартуларды табу сәтсіз аяқталды",
        "IP of PC":"Компьютердің IP мекенжайы",
        "Your IP":"Сіздің IP мекенжайыңыз",
        "Connect":"Қосылу",
        "How to use \nDashboard?":"Басқару тақтасын қалай пайдалану керек?",
        "What new \nin SerOS?":"SerOS-та не жаңа бар?",
        "Your PC isn't needing to update now":"Сіздің компьютеріңіз қазір жаңартуды қажет етпейді",
        "User of PC":"Компьютер пайдаланушысы",
        "Open a program in PC":"Компьютерде бағдарламаны ашу",
        "Add": "Қосу",
        "Remove": "Алау",
        "Open": "Ашу",
        "Play": "Ойнату",
        "Stop": "Тоқтату",
        "List": "Тізім"
    },
    "ko_KR":{
        "Home":"홈",
        "Updating":"업데이트",
        "Remote connection":"원격 연결",
        "About":"정보",
        "Welcome to Dashboard":"대시보드에 오신 것을 환영합니다",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"대시보드\n작성자: OrgInfoTech @2024\n버전: 1.0.0 (01/01/2024)",
        "Update packages":"패키지 업데이트",
        "Downloads updates":"업데이트 다운로드",
        "To do all":"모두 실행",
        "Checking ...":"확인 중...",
        "You should to install updates for your PC":"PC에 업데이트를 설치해야 합니다",
        "Finding of updates was failed":"업데이트 찾기에 실패했습니다",
        "IP of PC":"PC IP",
        "Your IP":"사용자 IP",
        "Connect":"연결",
        "How to use \nDashboard?":"대시보드 사용 방법?",
        "What new \nin SerOS?":"SerOS의 새로운 기능은?",
        "Your PC isn't needing to update now":"현재 PC 업데이트가 필요하지 않습니다",
        "User of PC":"PC 사용자",
        "Open a program in PC":"PC에서 프로그램 열기",
        "Add": "추가",
        "Remove": "제거",
        "Open": "열기",
        "Play": "재생",
        "Stop": "정지",
        "List": "목록"
    },
    "ky_KG":{
        "Home":"Башкы бет",
        "Updating":"Жаңыртуу",
        "Remote connection":"Алыстан туташуу",
        "About":"Тууралуу",
        "Welcome to Dashboard":"Башкаруу тактасына кош келиңиз",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Башкаруу тактасы\nАвтору: OrgInfoTech @2024\nВерсиясы: 1.0.0 (01/01/2024)",
        "Update packages":"Пакеттерди жаңыртуу",
        "Downloads updates":"Жаңыртууларды жүктөп алуу",
        "To do all":"Баарын аткаруу",
        "Checking ...":"Текшерүүдө...",
        "You should to install updates for your PC":"Компьютериңизге жаңыртууларды орнотушуңуз керек",
        "Finding of updates was failed":"Жаңыртууларды табуу ийгиликсиз аяктады",
        "IP of PC":"Компьютердин IP дареги",
        "Your IP":"Сиздин IP дарегиңиз",
        "Connect":"Туташуу",
        "How to use \nDashboard?":"Башкаруу тактасын кантип колдонсо болот?",
        "What new \nin SerOS?":"SerOS'то эмнелер жаңы?",
        "Your PC isn't needing to update now":"Компьютериңиз азыр жаңыртууну талап кылбайт",
        "User of PC":"Компьютердин колдонуучусу",
        "Open a program in PC":"Компьютерде программаны ачуу",
        "Add": "Кошуу",
        "Remove": "Өчүрүү",
        "Open": "Ачуу",
        "Play": "Ойнотуу",
        "Stop": "Токтотуу",
        "List": "Тизме"
    },
    "lv_LV":{
        "Home":"Sākums",
        "Updating":"Atjaunināšana",
        "Remote connection":"Attālā savienojums",
        "About":"Par",
        "Welcome to Dashboard":"Laipni lūdzam informācijas panelī",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Informācijas panelis\nAutors: OrgInfoTech @2024\nVersija: 1.0.0 (01/01/2024)",
        "Update packages":"Atjaunināt pakotnes",
        "Downloads updates":"Lejupielādēt atjauninājumus",
        "To do all":"Izpildīt visu",
        "Checking ...":"Pārbaude...",
        "You should to install updates for your PC":"Jums vajadzētu instalēt atjauninājumus savam datoram",
        "Finding of updates was failed":"Atjauninājumu meklēšana neizdevās",
        "IP of PC":"Datora IP",
        "Your IP":"Jūsu IP",
        "Connect":"Savienot",
        "How to use \nDashboard?":"Kā izmantot informācijas paneli?",
        "What new \nin SerOS?":"Kas jauns SerOS?",
        "Your PC isn't needing to update now":"Jūsu datoram pašlaik nav nepieciešams atjauninājums",
        "User of PC":"Datora lietotājs",
        "Open a program in PC":"Atvērt programmu datorā",
        "Add": "Pievienot",
        "Remove": "Noņemt",
        "Open": "Atvērt",
        "Play": "Atskaņot",
        "Stop": "Apturēt",
        "List": "Saraksts"
    },
    "lt_LT":{
        "Home":"Pradžia",
        "Updating":"Atnaujinimas",
        "Remote connection":"Nuotolinis ryšys",
        "About":"Apie",
        "Welcome to Dashboard":"Sveiki atvykę į informacinę lentelę",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Informacinė lentelė\nAutorius: OrgInfoTech @2024\nVersija: 1.0.0 (01/01/2024)",
        "Update packages":"Atnaujinti paketus",
        "Downloads updates":"Atsisiųsti atnaujinimus",
        "To do all":"Atlikti viską",
        "Checking ...":"Tikrinama...",
        "You should to install updates for your PC":"Turėtumėte įdiegti atnaujinimus savo kompiuteriui",
        "Finding of updates was failed":"Nepavyko rasti atnaujinimų",
        "IP of PC":"Kompiuterio IP",
        "Your IP":"Jūsų IP",
        "Connect":"Prisijungti",
        "How to use \nDashboard?":"Kaip naudotis informacine lentele?",
        "What new \nin SerOS?":"Kas naujo SerOS?",
        "Your PC isn't needing to update now":"Jūsų kompiuteriui dabar nereikia atnaujinimo",
        "User of PC":"Kompiuterio naudotojas",
        "Open a program in PC":"Atidaryti programą kompiuteryje",
        "Add": "Pridėti",
        "Remove": "Pašalinti",
        "Open": "Atidaryti",
        "Play": "Paleisti",
        "Stop": "Sustabdyti",
        "List": "Sąrašas"
    },
    "mn_MN":{
        "Home":"Нүүр хуудас",
        "Updating":"Шинэчлэлт",
        "Remote connection":"Уралдаан холболт",
        "About":"Тухай",
        "Welcome to Dashboard":"Мэдээллийн самбарлагдсан танд тавтай морилно уу",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Мэдээллийн самбар\nЗохиогч: OrgInfoTech @2024\nХувилбар: 1.0.0 (01/01/2024)",
        "Update packages":"Багцуудыг шинэчлэх",
        "Downloads updates":"Шинэчлэлтийг татаж авах",
        "To do all":"Бүгдийг хийх",
        "Checking ...":"Шалгаж байна...",
        "You should to install updates for your PC":"Таны компьютерт шинэчлэлт суулгах шаардлагатай",
        "Finding of updates was failed":"Шинэчлэлтийг олох амжилтгүй боллоо",
        "IP of PC":"Компьютерийн IP",
        "Your IP":"Таны IP",
        "Connect":"Холбогдох",
        "How to use \nDashboard?":"Мэдээллийн самбарыг хэрхэн ашиглах вэ?",
        "What new \nin SerOS?":"SerOS дээр юу шинэ байна?",
        "Your PC isn't needing to update now":"Таны компьютер одоо шинэчлэх шаардлагагүй байна",
        "User of PC":"Компьютерийн хэрэглэгч",
        "Open a program in PC":"Программ нээх компьютер",
        "Add": "Нэмэх",
        "Remove": "Устгах",
        "Open": "Нээх",
        "Play": "Тоглуулах",
        "Stop": "Зогсоох",
        "List": "Жагсаалт"
    },
    "fa_IR":{
        "Home":"خانه",
        "Updating":"به‌روزرسانی",
        "Remote connection":"اتصال از راه دور",
        "About":"درباره",
        "Welcome to Dashboard":"خوش آمدید به داشبورد",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"داشبورد\nنویسنده: OrgInfoTech @2024\nنسخه: 1.0.0 (01/01/2024)",
        "Update packages":"به‌روزرسانی بسته‌ها",
        "Downloads updates":"دانلود به‌روزرسانی‌ها",
        "To do all":"انجام همه",
        "Checking ...":"در حال بررسی...",
        "You should to install updates for your PC":"شما باید به‌روزرسانی‌ها را برای کامپیوتر خود نصب کنید",
        "Finding of updates was failed":"یافتن به‌روزرسانی‌ها ناموفق بود",
        "IP of PC":"IP کامپیوتر",
        "Your IP":"IP شما",
        "Connect":"اتصال",
        "How to use \nDashboard?":"چگونه از داشبورد استفاده کنیم؟",
        "What new \nin SerOS?":"چه خبری در SerOS وجود دارد؟",
        "Your PC isn't needing to update now":"کامپیوتر شما در حال حاضر نیازی به به‌روزرسانی ندارد",
        "User of PC":"کاربر کامپیوتر",
        "Open a program in PC":"باز کردن یک برنامه در کامپیوتر",
        "Add": "افزودن",
        "Remove": "حذف کردن",
        "Open": "باز کردن",
        "Play": "پخش",
        "Stop": "توقف",
        "List": "فهرست"
    },
    "pl_PL":{
        "Home":"Strona główna",
        "Updating":"Aktualizacja",
        "Remote connection":"Połączenie zdalne",
        "About":"O",
        "Welcome to Dashboard":"Witamy w panelu sterowania",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Panel sterowania\nAutor: OrgInfoTech @2024\nWersja: 1.0.0 (01/01/2024)",
        "Update packages":"Aktualizuj pakiety",
        "Downloads updates":"Pobierz aktualizacje",
        "To do all":"Wykonaj wszystko",
        "Checking ...":"Sprawdzanie...",
        "You should to install updates for your PC":"Powinieneś zainstalować aktualizacje dla swojego komputera",
        "Finding of updates was failed":"Wyszukiwanie aktualizacji nie powiodło się",
        "IP of PC":"IP komputera",
        "Your IP":"Twój adres IP",
        "Connect":"Połącz",
        "How to use \nDashboard?":"Jak korzystać z panelu sterowania?",
        "What new \nin SerOS?":"Co nowego w SerOS?",
        "Your PC isn't needing to update now":"Twój komputer nie wymaga aktualizacji w tej chwili",
        "User of PC":"Użytkownik komputera",
        "Open a program in PC":"Otwórz program na komputerze",
        "Add": "Dodaj",
        "Remove": "Usuń",
        "Open": "Otwórz",
        "Play": "Odtwórz",
        "Stop": "Zatrzymaj",
        "List": "Lista"
    },
    "pt_PT":{
        "Home":"Início",
        "Updating":"Atualizar",
        "Remote connection":"Conexão remota",
        "About":"Sobre",
        "Welcome to Dashboard":"Bem-vindo ao Painel de Controlo",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Painel de Controlo\nAutor: OrgInfoTech @2024\nVersão: 1.0.0 (01/01/2024)",
        "Update packages":"Atualizar pacotes",
        "Downloads updates":"Transferir atualizações",
        "To do all":"Fazer tudo",
        "Checking ...":"A verificar...",
        "You should to install updates for your PC":"Deve instalar as atualizações para o seu computador",
        "Finding of updates was failed":"A procura de atualizações falhou",
        "IP of PC":"IP do computador",
        "Your IP":"O seu IP",
        "Connect":"Ligar",
        "How to use \nDashboard?":"Como usar o Painel de Controlo?",
        "What new \nin SerOS?":"O que há de novo no SerOS?",
        "Your PC isn't needing to update now":"O seu computador não precisa de atualização agora",
        "User of PC":"Utilizador do computador",
        "Open a program in PC":"Abrir um programa no computador",
        "Add": "Adicionar",
        "Remove": "Remover",
        "Open": "Abrir",
        "Play": "Reproduzir",
        "Stop": "Parar",
        "List": "Lista"
    },
    "pt_BR":{
        "Home":"Início",
        "Updating":"Atualização",
        "Remote connection":"Conexão remota",
        "About":"Sobre",
        "Welcome to Dashboard":"Bem-vindo ao Painel de Controle",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Painel de Controle\nAutor: OrgInfoTech @2024\nVersão: 1.0.0 (01/01/2024)",
        "Update packages":"Atualizar pacotes",
        "Downloads updates":"Baixar atualizações",
        "To do all":"Executar tudo",
        "Checking ...":"Verificando...",
        "You should to install updates for your PC":"Você deve instalar as atualizações para o seu computador",
        "Finding of updates was failed":"Falha ao encontrar atualizações",
        "IP of PC":"IP do computador",
        "Your IP":"Seu IP",
        "Connect":"Conectar",
        "How to use \nDashboard?":"Como usar o Painel de Controle?",
        "What new \nin SerOS?":"O que há de novo no SerOS?",
        "Your PC isn't needing to update now":"Seu computador não precisa de atualização no momento",
        "User of PC":"Usuário do computador",
        "Open a program in PC":"Abrir um programa no computador",
        "Add": "Adicionar",
        "Remove": "Remover",
        "Open": "Abrir",
        "Play": "Reproduzir",
        "Stop": "Parar",
        "List": "Lista"
    },
    "ro_RO":{
        "Home":"Acasă",
        "Updating":"Actualizare",
        "Remote connection":"Conexiune la distanță",
        "About":"Despre",
        "Welcome to Dashboard":"Bine ați venit la Tabloul de Bord",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Tabloul de Bord\nAutor: OrgInfoTech @2024\nVersiune: 1.0.0 (01/01/2024)",
        "Update packages":"Actualizare pachete",
        "Downloads updates":"Descărcare actualizări",
        "To do all":"A face tot",
        "Checking ...":"Verificare...",
        "You should to install updates for your PC":"Ar trebui să instalați actualizările pentru calculatorul dvs.",
        "Finding of updates was failed":"Căutarea actualizărilor a eșuat",
        "IP of PC":"IP-ul calculatorului",
        "Your IP":"IP-ul dvs.",
        "Connect":"Conectare",
        "How to use \nDashboard?":"Cum să folosiți Tabloul de Bord?",
        "What new \nin SerOS?":"Ce este nou în SerOS?",
        "Your PC isn't needing to update now":"Calculatorul dvs. nu are nevoie de actualizare acum",
        "User of PC":"Utilizatorul calculatorului",
        "Open a program in PC":"Deschideți un program în calculator",
        "Add": "Adăugare",
        "Remove": "Eliminare",
        "Open": "Deschide",
        "Play": "Redare",
        "Stop": "Stop",
        "List": "Listă"
    },
    "ru_RU":{
        "Home":"Главная",
        "Updating":"Обновление",
        "Remote connection":"Удаленное подключение",
        "About":"О программе",
        "Welcome to Dashboard":"Добро пожаловать в панель управления",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Панель управления\nАвтор: OrgInfoTech @2024\nВерсия: 1.0.0 (01/01/2024)",
        "Update packages":"Обновить пакеты",
        "Downloads updates":"Загрузить обновления",
        "To do all":"Выполнить все",
        "Checking ...":"Проверка...",
        "You should to install updates for your PC":"Вам следует установить обновления для вашего компьютера",
        "Finding of updates was failed":"Не удалось найти обновления",
        "IP of PC":"IP-адрес компьютера",
        "Your IP":"Ваш IP-адрес",
        "Connect":"Подключиться",
        "How to use \nDashboard?":"Как пользоваться панелью управления?",
        "What new \nin SerOS?":"Что нового в SerOS?",
        "Your PC isn't needing to update now":"Вашему компьютеру сейчас не требуется обновление",
        "User of PC":"Пользователь компьютера",
        "Open a program in PC":"Открыть программу на компьютере",
        "Add": "Добавить",
        "Remove": "Удалить",
        "Open": "Открыть",
        "Play": "Воспроизвести",
        "Stop": "Остановить",
        "List": "Список"
    },
    "sr_RS":{
        "Home":"Почетна",
        "Updating":"Ажурирање",
        "Remote connection":"Удаљена веза",
        "About":"О",
        "Welcome to Dashboard":"Добродошли на контролну таблу",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Контролна табла\nАутор: OrgInfoTech @2024\nВерзија: 1.0.0 (01/01/2024)",
        "Update packages":"Ажурирај пакете",
        "Downloads updates":"Преузми ажурирања",
        "To do all":"Уради све",
        "Checking ...":"Провера...",
        "You should to install updates for your PC":"Треба да инсталирате ажурирања за ваш рачунар",
        "Finding of updates was failed":"Проналажење ажурирања није успело",
        "IP of PC":"IP рачунара",
        "Your IP":"Ваш IP",
        "Connect":"Повежи се",
        "How to use \nDashboard?":"Како користити контролну таблу?",
        "What new \nin SerOS?":"Шта је ново у SerOS?",
        "Your PC isn't needing to update now":"Вашем рачунару тренутно није потребно ажурирање",
        "User of PC":"Корисник рачунара",
        "Open a program in PC":"Отвори програм на рачунару",
        "Add": "Додај",
        "Remove": "Уклони",
        "Open": "Отвори",
        "Play": "Покрени",
        "Stop": "Стоп",
        "List": "Листа"
    },
    "sr_RS_latin":{
        "Home":"Početna",
        "Updating":"Ažuriranje",
        "Remote connection":"Udaljena veza",
        "About":"O nama",
        "Welcome to Dashboard":"Dobrodošli na kontrolnu tablu",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Kontrolna tabla\nAutor: OrgInfoTech @2024\nVerzija: 1.0.0 (01/01/2024)",
        "Update packages":"Ažuriraj pakete",
        "Downloads updates":"Preuzmi ažuriranja",
        "To do all":"Obavi sve",
        "Checking ...":"Provera...",
        "You should to install updates for your PC":"Treba da instalirate ažuriranja za vaš računar",
        "Finding of updates was failed":"Pronalaženje ažuriranja nije uspelo",
        "IP of PC":"IP računara",
        "Your IP":"Vaš IP",
        "Connect":"Poveži se",
        "How to use \nDashboard?":"Kako koristiti kontrolnu tablu?",
        "What new \nin SerOS?":"Šta je novo u SerOS-u?",
        "Your PC isn't needing to update now":"Vašem računaru trenutno nije potrebno ažuriranje",
        "User of PC":"Korisnik računara",
        "Open a program in PC":"Otvori program na računaru",
        "Add": "Dodaj",
        "Remove": "Ukloni",
        "Open": "Otvori",
        "Play": "Pokreni",
        "Stop": "Stop",
        "List": "Lista"
    },
    "sk_SK":{
        "Home":"Domov",
        "Updating":"Aktualizácia",
        "Remote connection":"Vzdialené pripojenie",
        "About":"O nás",
        "Welcome to Dashboard":"Vitajte na ovládacom paneli",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Ovládací panel\nAutor: OrgInfoTech @2024\nVerzia: 1.0.0 (01/01/2024)",
        "Update packages":"Aktualizovať balíky",
        "Downloads updates":"Stiahnuť aktualizácie",
        "To do all":"Vykonať všetko",
        "Checking ...":"Kontrola...",
        "You should to install updates for your PC":"Mali by ste nainštalovať aktualizácie pre váš počítač",
        "Finding of updates was failed":"Nepodarilo sa nájsť aktualizácie",
        "IP of PC":"IP počítača",
        "Your IP":"Vaša IP adresa",
        "Connect":"Pripojiť",
        "How to use \nDashboard?":"Ako používať ovládací panel?",
        "What new \nin SerOS?":"Čo je nové v SerOS?",
        "Your PC isn't needing to update now":"Váš počítač v súčasnosti nepotrebuje aktualizáciu",
        "User of PC":"Používateľ počítača",
        "Open a program in PC":"Otvoriť program v počítači",
        "Add": "Pridať",
        "Remove": "Odstrániť",
        "Open": "Otvoriť",
        "Play": "Prehrať",
        "Stop": "Zastaviť",
        "List": "Zoznam"
    },
    "sl_SI":{
        "Home":"Domov",
        "Updating":"Posodabljanje",
        "Remote connection":"Oddaljeno povezovanje",
        "About":"O programu",
        "Welcome to Dashboard":"Dobrodošli v nadzorni plošči",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Nadzorna plošča\nAvtor: OrgInfoTech @2024\nRazličica: 1.0.0 (01/01/2024)",
        "Update packages":"Posodobi pakete",
        "Downloads updates":"Prenesi posodobitve",
        "To do all":"Naredi vse",
        "Checking ...":"Preverjanje...",
        "You should to install updates for your PC":"Namestiti bi morali posodobitve za vaš računalnik",
        "Finding of updates was failed":"Iskanje posodobitev ni uspelo",
        "IP of PC":"IP računalnika",
        "Your IP":"Vaš IP",
        "Connect":"Poveži se",
        "How to use \nDashboard?":"Kako uporabljati nadzorno ploščo?",
        "What new \nin SerOS?":"Kaj je novega v SerOS?",
        "Your PC isn't needing to update now":"Vaš računalnik trenutno ne potrebuje posodobitve",
        "User of PC":"Uporabnik računalnika",
        "Open a program in PC":"Odpri program v računalniku",
        "Add": "Dodaj",
        "Remove": "Odstrani",
        "Open": "Odpri",
        "Play": "Predvajaj",
        "Stop": "Ustavi",
        "List": "Seznam"
    },
    "es_ES":{
        "Home":"Inicio",
        "Updating":"Actualización",
        "Remote connection":"Conexión remota",
        "About":"Acerca de",
        "Welcome to Dashboard":"Bienvenido al Panel de Control",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Panel de Control\nAutor: OrgInfoTech @2024\nVersión: 1.0.0 (01/01/2024)",
        "Update packages":"Actualizar paquetes",
        "Downloads updates":"Descargar actualizaciones",
        "To do all":"Hacer todo",
        "Checking ...":"Comprobando...",
        "You should to install updates for your PC":"Deberías instalar las actualizaciones para tu PC",
        "Finding of updates was failed":"No se pudieron encontrar actualizaciones",
        "IP of PC":"IP del PC",
        "Your IP":"Tu IP",
        "Connect":"Conectar",
        "How to use \nDashboard?":"¿Cómo usar el Panel de Control?",
        "What new \nin SerOS?":"¿Qué hay de nuevo en SerOS?",
        "Your PC isn't needing to update now":"Tu PC no necesita actualizarse ahora",
        "User of PC":"Usuario del PC",
        "Open a program in PC":"Abrir un programa en el PC",
        "Add": "Agregar",
        "Remove": "Eliminar",
        "Open": "Abrir",
        "Play": "Reproducir",
        "Stop": "Detener",
        "List": "Lista"
    },
    "sv_SE":{
        "Home":"Hem",
        "Updating":"Uppdatering",
        "Remote connection":"Fjärranslutning",
        "About":"Om",
        "Welcome to Dashboard":"Välkommen till instrumentpanelen",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Instrumentpanel\nFörfattare: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)",
        "Update packages":"Uppdatera paket",
        "Downloads updates":"Ladda ner uppdateringar",
        "To do all":"Utför alla",
        "Checking ...":"Kontrollerar...",
        "You should to install updates for your PC":"Du bör installera uppdateringar för din dator",
        "Finding of updates was failed":"Sökning efter uppdateringar misslyckades",
        "IP of PC":"Datorns IP",
        "Your IP":"Din IP",
        "Connect":"Anslut",
        "How to use \nDashboard?":"Hur använder man instrumentpanelen?",
        "What new \nin SerOS?":"Vad är nytt i SerOS?",
        "Your PC isn't needing to update now":"Din dator behöver inte uppdateras just nu",
        "User of PC":"Datoranvändare",
        "Open a program in PC":"Öppna ett program på datorn",
        "Add": "Lägg till",
        "Remove": "Ta bort",
        "Open": "Öppna",
        "Play": "Spela",
        "Stop": "Stoppa",
        "List": "Lista"
    },
    "tt_RU":{
        "Home":"Баш бит",
        "Updating":"Яңарту",
        "Remote connection":"Ерактан тоташу",
        "About":"Турында",
        "Welcome to Dashboard":"Идарә панеленә рәхим итегез",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Идарә панеле\nАвтор: OrgInfoTech @2024\nВерсия: 1.0.0 (01/01/2024)",
        "Update packages":"Пакетларны яңарту",
        "Downloads updates":"Яңартуларны йөкләү",
        "To do all":"Барысын да башкару",
        "Checking ...":"Тикшерү...",
        "You should to install updates for your PC":"Сезгә компьютерыгыз өчен яңартуларны урнаштыру кирәк",
        "Finding of updates was failed":"Яңартуларны табу уңышсыз булды",
        "IP of PC":"Компьютер IP-адресы",
        "Your IP":"Сезнең IP-адрес",
        "Connect":"Тоташу",
        "How to use \nDashboard?":"Идарә панелен ничек кулланырга?",
        "What new \nin SerOS?":"SerOS'та нәрсә яңа?",
        "Your PC isn't needing to update now":"Хәзерге вакытта сезнең компьютерыгызга яңарту кирәк түгел",
        "User of PC":"Компьютер кулланучысы",
        "Open a program in PC":"Компьютердә программа ачу",
        "Add": "Өстәү",
        "Remove": "Бетерү",
        "Open": "Ачу",
        "Play": "Ойнату",
        "Stop": "Токтату",
        "List": "Тизем"
    },
    "th_TH":{
        "Home":"หน้าหลัก",
        "Updating":"อัปเดต",
        "Remote connection":"การเชื่อมต่อระยะไกล",
        "About":"เกี่ยวกับ",
        "Welcome to Dashboard":"ยินดีต้อนรับสู่แดชบอร์ด",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"แดชบอร์ด\nผู้เขียน: OrgInfoTech @2024\nเวอร์ชัน: 1.0.0 (01/01/2024)",
        "Update packages":"อัปเดตแพ็คเกจ",
        "Downloads updates":"ดาวน์โหลดอัปเดต",
        "To do all":"ทำทั้งหมด",
        "Checking ...":"กำลังตรวจสอบ...",
        "You should to install updates for your PC":"คุณควรติดตั้งอัปเดตสำหรับคอมพิวเตอร์ของคุณ",
        "Finding of updates was failed":"การค้นหาอัปเดตล้มเหลว",
        "IP of PC":"IP ของคอมพิวเตอร์",
        "Your IP":"IP ของคุณ",
        "Connect":"เชื่อมต่อ",
        "How to use \nDashboard?":"วิธีใช้แดชบอร์ด?",
        "What new \nin SerOS?":"มีอะไรใหม่ใน SerOS?",
        "Your PC isn't needing to update now":"คอมพิวเตอร์ของคุณไม่จำเป็นต้องอัปเดตในขณะนี้",
        "User of PC":"ผู้ใช้คอมพิวเตอร์",
        "Open a program in PC":"เปิดโปรแกรมในคอมพิวเตอร์",
        "Add": "เพิ่ม",
        "Remove": "ลบ",
        "Open": "เปิด",
        "Play": "เล่น",
        "Stop": "หยุด",
        "List": "รายการ"
    },
    "bo_CN":{
        "Home":"གདོང་ཤོག",
        "Updating":"སྱིན་བཅོས་བྱེད་པ།",
        "Remote connection":"རྒྱང་ཐག་ནས་མཐུད་པ།",
        "About":"སྐོར་ལ།",
        "Welcome to Dashboard":"ཡིག་ཆ་ཁང་ལ་དགའ་བསུ་ཞུ།",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"ཡིག་ཆ་ཁང་།\nམཁས་པ། OrgInfoTech @2024\nཐོན་རིམ། 1.0.0 (01/01/2024)",
        "Update packages":"སྱིན་བཅོས་ཆ་ཚང་།",
        "Downloads updates":"སྱིན་བཅོས་ཕབ་ལེན་བྱེད་པ།",
        "To do all":"ཚང་མ་བྱེད་པ།",
        "Checking ...":"ཞིབ་འཇུག་བྱེད་བཞིན་པ།...",
        "You should to install updates for your PC":"ཁྱོད་ཀྱི་འགོག་རྟགས་ཀྱི་སྱིན་བཅོས་འཇོག་དགོས།",
        "Finding of updates was failed":"སྱིན་བཅོས་འཚོལ་ཞིབ་ཕམ་པ།",
        "IP of PC":"འགོག་རྟགས་ཀྱི་IP",
        "Your IP":"ཁྱོད་ཀྱི་IP",
        "Connect":"མཐུད་པ།",
        "How to use \nDashboard?":"ཡིག་ཆ་ཁང་ཇི་ལྟར་སྤྱོད་ན།",
        "What new \nin SerOS?":"SerOS ནང་གི་གསར་པ་ཅི་ཡོད།",
        "Your PC isn't needing to update now":"ཁྱོད་ཀྱི་འགོག་རྟགས་ལ་ད་ལྟ་སྱིན་བཅོས་དགོས་མི་དགོས།",
        "User of PC":"འགོག་རྟགས་ཀྱི་སྤྱོད་མཁན།",
        "Open a program in PC":"འགོག་རྟགས་ནང་ལས་རིམ་ཞིག་ཁ་ཕྱེ་བ།",
        "Add": "བཙལ་བ",
        "Remove": "བཏོན་བ",
        "Open": "བརྟེན་བ",
        "Play": "ཕོད་སྡོམ་བ",
        "Stop": "རིམ་བཏགས་པ",
        "List": "ཐོག་གཅོད།"
    },
    "tr_TR":{
        "Home":"Ana Sayfa",
        "Updating":"Güncelleme",
        "Remote connection":"Uzaktan bağlantı",
        "About":"Hakkında",
        "Welcome to Dashboard":"Kontrol Paneline Hoş Geldiniz",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Kontrol Paneli\nYazar: OrgInfoTech @2024\nSürüm: 1.0.0 (01/01/2024)",
        "Update packages":"Paketleri Güncelle",
        "Downloads updates":"Güncellemeleri İndir",
        "To do all":"Hepsini yap",
        "Checking ...":"Kontrol ediliyor...",
        "You should to install updates for your PC":"Bilgisayarınız için güncellemeleri yüklemeniz gerekmektedir",
        "Finding of updates was failed":"Güncellemelerin bulunması başarısız oldu",
        "IP of PC":"Bilgisayarın IP adresi",
        "Your IP":"Sizin IP'niz",
        "Connect":"Bağlan",
        "How to use \nDashboard?":"Kontrol Paneli nasıl kullanılır?",
        "What new \nin SerOS?":"SerOS'ta neler yeni?",
        "Your PC isn't needing to update now":"Bilgisayarınız şu anda güncellemeye ihtiyaç duymuyor",
        "User of PC":"Bilgisayar kullanıcısı",
        "Open a program in PC":"Bilgisayarda bir program aç",
        "Add": "Ekle",
        "Remove": "Kaldır",
        "Open": "Aç",
        "Play": "Oynat",
        "Stop": "Dur",
        "List": "Liste"
    },
    "tk_TM":{
        "Home":"Baş Sahypa",
        "Updating":"Täzelme",
        "Remote connection":"Uzak baglanyşyk",
        "About":"Hakynda",
        "Welcome to Dashboard":"Panela Hoş Geldiňiz",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Panel\nAwtor: OrgInfoTech @2024\nWersiýa: 1.0.0 (01/01/2024)",
        "Update packages":"Paketleri täzelen",
        "Downloads updates":"Täzelenmeleri ýükle",
        "To do all":"Ähli zatlar",
        "Checking ...":"Barlaýyş...",
        "You should to install updates for your PC":"Bilgisunyňyz üçin täzelenmeleri yüklemeli",
        "Finding of updates was failed":"Täzelenmeler tapylmady",
        "IP of PC":"Bilgisunyň IP",
        "Your IP":"Sizin IP",
        "Connect":"Baglanyň",
        "How to use \nDashboard?":"Paneli näme üçin ulanmaly?",
        "What new \nin SerOS?":"SerOS-da näme täze?",
        "Your PC isn't needing to update now":"Bilgisunyňyz şu wagtda täzelenmäge ihtiyaryok",
        "User of PC":"Bilgisun ulanyjysy",
        "Open a program in PC":"Bilgisunyňda programma aç",
        "Add": "Goşmak",
        "Remove": "Aýyrmak",
        "Open": "Açmak",
        "Play": "Oýnamak",
        "Stop": "Durdurmak",
        "List": "Sanaw"
    },
    "uk_UA":{
        "Home":"Головна",
        "Updating":"Оновлення",
        "Remote connection":"Віддалене підключення",
        "About":"Про програму",
        "Welcome to Dashboard":"Ласкаво просимо до панелі керування",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Панель керування\nАвтор: OrgInfoTech @2024\nВерсія: 1.0.0 (01/01/2024)",
        "Update packages":"Оновити пакети",
        "Downloads updates":"Завантажити оновлення",
        "To do all":"Виконати все",
        "Checking ...":"Перевірка...",
        "You should to install updates for your PC":"Вам слід встановити оновлення для вашого комп'ютера",
        "Finding of updates was failed":"Пошук оновлень не вдався",
        "IP of PC":"IP-адреса комп'ютера",
        "Your IP":"Ваш IP",
        "Connect":"Підключитися",
        "How to use \nDashboard?":"Як користуватися панеллю керування?",
        "What new \nin SerOS?":"Що нового в SerOS?",
        "Your PC isn't needing to update now":"Вашому комп'ютеру зараз не потрібно оновлення",
        "User of PC":"Користувач комп'ютера",
        "Open a program in PC":"Відкрити програму на комп'ютері",
        "Add": "Додати",
        "Remove": "Видалити",
        "Open": "Відкрити",
        "Play": "Відтворити",
        "Stop": "Зупинити",
        "List": "Список"
    },
    "ur_PK":{
        "Home":"ہوم",
        "Updating":"اپ ڈیٹ",
        "Remote connection":"ریموٹ کنکشن",
        "About":"کے بارے میں",
        "Welcome to Dashboard":"ڈیش بورڈ میں خوش آمدید",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"ڈیش بورڈ\nمصنف: OrgInfoTech @2024\nورژن: 1.0.0 (01/01/2024)",
        "Update packages":"پیکیجز کو اپ ڈیٹ کریں",
        "Downloads updates":"اپ ڈیٹس ڈاؤن لوڈ کریں",
        "To do all":"سب کچھ کرنا",
        "Checking ...":"چیک کر رہا ہے...",
        "You should to install updates for your PC":"آپ کو اپنے کمپیوٹر کے لیے اپ ڈیٹس انسٹال کرنے چاہیے",
        "Finding of updates was failed":"اپ ڈیٹس تلاش کرنے میں ناکامی",
        "IP of PC":"کمپیوٹر کا آئی پی",
        "Your IP":"آپ کا آئی پی",
        "Connect":"منسلک کریں",
        "How to use \nDashboard?":"ڈیش بورڈ کا استعمال کیسے کریں؟",
        "What new \nin SerOS?":"SerOS میں کیا نیا ہے؟",
        "Your PC isn't needing to update now":"آپ کے کمپیوٹر کو اب اپ ڈیٹ کی ضرورت نہیں ہے",
        "User of PC":"کمپیوٹر کا صارف",
        "Open a program in PC":"کمپیوٹر میں ایک پروگرام کھولیں",
        "Add": "شامل کریں",
        "Remove": "ہٹائیں",
        "Open": "کھولیں",
        "Play": "چلائیں",
        "Stop": "روکیں",
        "List": "فہرست"
    },
    "ug_CN":{
        "Home":"باش بەت",
        "Updating":"يېڭىلانما",
        "Remote connection":"يىراق باغلانما",
        "About":"تەھرىر",
        "Welcome to Dashboard":"باشقۇرغۇچ تاختىغا خۇش كەلدىڭىز",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"باشقۇرغۇچ\nئاپتور: OrgInfoTech @2024\nنەشرى: 1.0.0 (01/01/2024)",
        "Update packages":"پاكەتلەرنى يېڭىلا",
        "Downloads updates":"يېڭىلانمىنى چۈشۈر",
        "To do all":"ھەممىسىنى ئىجرا قىلىش",
        "Checking ...":"تەكشۈرۈۋاتىدۇ...",
        "You should to install updates for your PC":"كومپيۇتېرىڭىزغا يېڭىلانمىنى قويۇشىڭىز كېرەك",
        "Finding of updates was failed":"يېڭىلانمىنى تاپقاندا خاتالىق كۆرۈلدى",
        "IP of PC":"كومپيۇتېر IP",
        "Your IP":"سىزنىڭ IP",
        "Connect":"باغلان",
        "How to use \nDashboard?":"باشقۇرغۇچنى قانداق ئىشلەتمەك؟",
        "What new \nin SerOS?":"SerOS دا يېڭى نەدە؟",
        "Your PC isn't needing to update now":"كومپيۇتېرىڭىزغا ئىناۋەتلىك يېڭىلاش كىرەك ئىمدى",
        "User of PC":"كومپيۇتېر ئىشلەتكۈچىسى",
        "Open a program in PC":"كومپيۇتېردا دېپىنى ئاچ",
        "Add": "قوشۇش",
        "Remove": "چىقىرىش",
        "Open": "ئېچىش",
        "Play": "ئېلىش",
        "Stop": "توختىتىش",
        "List": "تىزىملىك"
    },
    "uz_UZ":{
        "Home":"Bosh sahifa",
        "Updating":"Yangilash",
        "Remote connection":"Uzoq aloqa",
        "About":"Haqida",
        "Welcome to Dashboard":"Boshqaruv paneliga xush kelibsiz",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Boshqaruv paneli\nMuallif: OrgInfoTech @2024\nVersiya: 1.0.0 (01/01/2024)",
        "Update packages":"Paketlarni yangilash",
        "Downloads updates":"Yangilanmalarni yuklash",
        "To do all":"Hammasini bajarish",
        "Checking ...":"Tekshirilmoqda...",
        "You should to install updates for your PC":"Kompyuteringiz uchun yangilanmalarni o'rnatishingiz kerak",
        "Finding of updates was failed":"Yangilanmalarni topish muvaffaqiyatsiz tugadi",
        "IP of PC":"Kompyuter IP manzili",
        "Your IP":"Sizning IP manzilingiz",
        "Connect":"Ulashing",
        "How to use \nDashboard?":"Boshqaruv panelidan qanday foydalanish mumkin?",
        "What new \nin SerOS?":"SerOS-da nima yangi?",
        "Your PC isn't needing to update now":"Sizning kompyuteringiz hozir yangilanishga ehtiyoj emas",
        "User of PC":"Kompyuter foydalanuvchisi",
        "Open a program in PC":"Kompyuterda dasturni ochish",
        "Add": "Qo'shish",
        "Remove": "Olib tashlash",
        "Open": "Ochish",
        "Play": "Ijro etish",
        "Stop": "To'xtatish",
        "List": "Ro'yxat"
    },
    "vi_VN":{
        "Home":"Trang chủ",
        "Updating":"Cập nhật",
        "Remote connection":"Kết nối từ xa",
        "About":"Về chúng tôi",
        "Welcome to Dashboard":"Chào mừng đến với bảng điều khiển",
        "Dashboard\nAuthor: OrgInfoTech @2024\nVersion: 1.0.0 (01/01/2024)":"Bảng điều khiển\nTác giả: OrgInfoTech @2024\nPhiên bản: 1.0.0 (01/01/2024)",
        "Update packages":"Cập nhật gói",
        "Downloads updates":"Tải xuống bản cập nhật",
        "To do all":"Thực hiện tất cả",
        "Checking ...":"Đang kiểm tra...",
        "You should to install updates for your PC":"Bạn nên cài đặt bản cập nhật cho máy tính của mình",
        "Finding of updates was failed":"Tìm kiếm bản cập nhật không thành công",
        "IP of PC":"IP của máy tính",
        "Your IP":"IP của bạn",
        "Connect":"Kết nối",
        "How to use \nDashboard?":"Cách sử dụng bảng điều khiển?",
        "What new \nin SerOS?":"Có gì mới trong SerOS?",
        "Your PC isn't needing to update now":"Máy tính của bạn hiện không cần cập nhật",
        "User of PC":"Người dùng máy tính",
        "Open a program in PC":"Mở một chương trình trên máy tính",
        "Add": "Thêm",
        "Remove": "Xóa",
        "Open": "Mở",
        "Play": "Phát",
        "Stop": "Dừng",
        "List": "Danh sách"
    }
}
